### ISSUE TITLE
table: improve column sorting accessibility

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#1011]
Use `aria-sort="[none/ascending/descending]"` to sortable column headers to indicate sort order.

Add screen reader only text "Sort [descending/ascending] by" to sortable headers to be read in addition to the column header label when they get focus.

~~A nice addition for visual users would be to add a tooltip when hovering over a sortable column header with the text "Sort [descending/ascending]" to make it very clear what sort order will happen when clicking.~~ _We'll address this later after some refinements are made to the tooltip._

**Comment by jaketrent** [comment]
@sweeting for the visual tooltip, should we use the native `title` for that?  Or our DS tooltip?  If DS tooltip, do you have a positing (eg, above or below) that you'd prefer?

**Comment by sweeting** [comment]
@jaketrent Let's hold off on adding the tooltip for now. There are some refinements I'd like to make to the tooltip first to better distinguish it from the dialog and make it work better on light theme.
