### ISSUE TITLE
defaultSort prop on Table.ColumnHeader

### ISSUE THREAD

**Issue by benallred** [pluralsight/design-system#1012]
It would be nice for `Table.ColumnHeader` to accept a `defaultSort` prop. In some cases we want a particular column to sort descending when clicked when it is not currently sorted. For example, we have an "Expert Users" column that we'd rather have sort descending when clicked the first time since admins are normally looking for the skill with the most experts (in this case).

**Comment by jaketrent** [comment]
Triage: Edward will contact Ben. Seems like props today will work for a "default sort" case. Need to get more details on the use case.

Docs:
https://design-system.pluralsight.com/components/table#sorting

**Comment by EdwardIrby** [comment]
Met with Ben and learned about his use case. I now understand his ask. Right now he is doing this https://design-system.pluralsight.com/components/table#sorting. It is possible we could make a hook that makes doing this easier that can be used in a manner similar to the Drawer RC or the new radio api. However, I don't think adding a new prop is a wise idea. Seems like prop creep. Adding topic to our retro.
