### ISSUE TITLE
Text.List: bulleted lists can not be nested in numbered lists

### ISSUE THREAD

**Issue by kameronperkins** [pluralsight/design-system#1021]
### Expected behavior

When nesting a list within a list it is expected that the nested list could be either `numbered` or `bulleted` and not dictated by its parent list.

This block, using html elements, renders the list with nesting as expected.
```html
<ol>
  <li>One</li>
  <li>Two</li>
  <ul>
    <li>first bullet</li>
    <li>second bullet</li>
  </ul>
  <li>Three</li>
</ol>
```

1. One
2. Two
- first bullet
- second bullet 
3. Three

### Actual behavior

When nesting a `bulleted` list within a `numbered` list the nested list should have bullet markers instead of numbered markers

This code

![image](https://user-images.githubusercontent.com/14792579/83567509-e8951200-a4de-11ea-87e7-71baa5200d50.png)

produces this

![image](https://user-images.githubusercontent.com/14792579/83566693-a7e8c900-a4dd-11ea-9dd3-ce8bf7ab7c72.png)

while nesting a numbered list within a bulleted list does this

![image](https://user-images.githubusercontent.com/14792579/83567672-2d20ad80-a4df-11ea-85bd-94fb2c9b8438.png)

![image](https://user-images.githubusercontent.com/14792579/83566802-d070c300-a4dd-11ea-9efa-ff2e88c19017.png)

### Steps to repro

1. Using Text.List from the design system nest a bulleted list inside a numbered list.

### Related packages

-text@16.0.4

### Environment

- OS - MacOS 10.15.4
- Browser version - Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by jaketrent** [comment]
Edward Triage: There was a minor bug. CSS wasn't quite right for nested lists. Open PR waiting for design input.
