### ISSUE TITLE
The Contribute page returns 404

### ISSUE THREAD

**Issue by vadimbakaev** [pluralsight/design-system#1027]
### Expected behavior

Get into Contribute from README

### Actual behavior

To get into the contribution page the steps are:

1. Navigate to https://design-system.pluralsight.com
2. Click to Contribute to the menu

But it's not accessible by direct link.

### Steps to repro

- Click to https://design-system.pluralsight.com/contribute

or

- Go to Contribute page and refresh it

### Related packages

documentation page

### Environment

- OS - MacOS 10.15.4
- Browser version - Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by jaketrent** [comment]
new url works https://design-system.pluralsight.com/guides/contribute. resolving
