### ISSUE TITLE
button: flat design spacing is off

### ISSUE THREAD

**Issue by bressain** [pluralsight/design-system#103]
### Expected behavior

When using the `flat` appearance, the button shouldn't add any additional horizontal layout space (see https://material.io/guidelines/components/buttons.html#buttons-flat-buttons). This allows for the button to look much like a link when not clicked and can align to edges more naturally.

### Actual behavior

Right now when using the `flat` appearance, the button horizontal spacing takes up space which pushes the button out from the edge of a component:

![screen shot 2017-09-11 at 2 15 32 pm](https://user-images.githubusercontent.com/938798/30298098-6233286a-9707-11e7-83af-6dd423312cc0.png)

### Steps to repro

1. Plop the button component in a component and attempt to line it up vertically with something above/below.
2. Run the component and witness the paddingalooza.

### Related packages

- button@8.0.6

**Comment by jaketrent** [comment]
^ thanks for the screenshot!

**Comment by jaketrent** [comment]
@dborodyansky any update on where this is at?

**Comment by dborodyansky** [comment]
Reviewed with design group, and we landed on the spacing not being a 'bug' but expected as to how these types of buttons would be used in context (primarily in an tool-bar-like array... this would benefit from more usage documentation on the site). Action items result in minor tweaks to backfill color (complete), and outstanding 'light theme' version TBD when we hit component theming.

**Comment by jaketrent** [comment]
@bressain design update ^
