### ISSUE TITLE
Autoposition utility & Tooltip refactor

### ISSUE THREAD

**Issue by EdwardIrby** [pluralsight/design-system#1036]
In regards to #932. The solution was to use BelowRight instead of Below because using below would cause the window width to change if the tooltip is wider than a target flexed to the right of the screen. After making this prop change the dev simply need to change the tip position to topRight. 

However this illustrates that a developer must be aware of where a target is on the screen in various context in which this position might change. A solution to this manual position management would be to allow portal like elements such as tooltip or dropdown to auto-position. 

To that effect I propose adding some auto-position utilities/hooks to the design system that can be used with these portal like elements.

**Comment by sweeting** [comment]
Can it just work like this? Position can be specified, but automatically handles viewport. https://codesandbox.io/s/6hc12

**Comment by jaketrent** [comment]
Triage:

- Remains: Still specify by design where the tooltip/other thing should go
- Add: Avoid clipping by shifting automatically

**Comment by EdwardIrby** [comment]
Cl
