### ISSUE TITLE
navitem: explore how to split out markup

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1037]
Goal: Supply non-React projects/products with as much support through nav DS as possible.

Existing: They already have CSS separately built.  We can split out logic easily enough as needed.  There likely won't be a lot in the nav stuff, but who knows.

Current criticality: I think this would be good for the *story* of nav and DS overall.  Currently, it likely is not critical because both products will likely have a React implementation.  But, maybe not.  We still don't know how they'll plan to share it.

`htm` lib is a solution that has been pitched previously.

Is there a solution that would work in prism today (hyperapp)?

**Comment by EdwardIrby** [comment]
Giving myself until noon Wednesday 7/15/20 to prototype this.
