### ISSUE TITLE
site: links to design assets are broken

### ISSUE THREAD

**Issue by pyzcko** [pluralsight/design-system#1093]
All links to the design assets files are broken.
https://design-system.pluralsight.com/design-assets

![Bildschirmfoto 2020-08-12 um 08 20 34](https://user-images.githubusercontent.com/33692517/89981773-c6ed9f00-dc74-11ea-81a7-9d5052b6a0ff.png)

**Comment by jaketrent** [comment]
New url is: https://design-system.pluralsight.com/guides/designworkflow

Seems to work for me.
