### ISSUE TITLE
ActionMenu: Fix hover styles

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1095]
### Expected behavior

- Light gray on mouse hover
- Blue on keyboard focus

### Actual behavior

- Light gray on mouse hover
- Blue on wrong item when hover off onto another item

### Steps to repro

1. Docs site, open in-app example ActionMenu
2. Hover over item 1
3. Hover over item 2, item 1 shows blue background

### Related packages

- actionmenu@14

### Environment

- OS - MacOS 10.14
- Browser version - Chrome

Have also seen this in my Flow nav work.

![hoverStylesMixedUp](https://user-images.githubusercontent.com/552044/90062919-b43f8e00-dca5-11ea-8c74-9d90ed456507.gif)

**Comment by EdwardIrby** [comment]
That's the correct behavior. You haven't refocused. BY using the arrow keys or clicking.

**Comment by jaketrent** [comment]
I'm really skeptical that this is the behavior we want.  

In the past the blue was reserved for focus state as in keyboard navigation.  

But the the thing that seems most wrong is that there remains a blue highlight on an item that's not the item I'm mouse-hovering on.  The mouse hover gets a light grey.  The blue remains much more apparent and thus seems to be highlighting the wrong thing.

@sweeting , will you give us a 2nd opinion on the intended UX related to the mouse/keyboard hover/focus behavior here, please?
