### ISSUE TITLE
core: Spacing var change - XLarge to 48, and XXLarge to 64

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#110]
### Desired behavior
XLarge spacing becomes 48px
XXLarge spacing becomes 64px

### Today's behavior
XLarge is currently 40px
XXLarge is currently 56px

### The Value Add

48 and 64 are mathematically cleaner and more divisible :)

### The Tradeoffs

Rippling change

**Comment by jaketrent** [comment]
dup of #113
