### ISSUE TITLE
actionmenu: origin=bottomRight is not working

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1100]
### Expected behavior

`origin=bottomRight` would put the actionmenu in the bottom right and grow from there toward the top left as nested menus are expanded.

### Actual behavior

Doesn't seem to be in the bottom right corner of the example, and grows the default direction *toward* the bottom right.

<img width="897" alt="Screen Shot 2020-08-14 at 7 07 08 AM" src="https://user-images.githubusercontent.com/552044/90252704-2d9dc480-ddfd-11ea-8896-212a89b7faac.png">

### Steps to repro

1. Open example: https://design-system.pluralsight.com/components/actionmenu#origin to observe

### Related packages

- actionmenu@14

**Comment by EdwardIrby** [comment]
I don't think that is correct. The origins are wrong but not that way topLeft I renamed topRight and the same for the bottoms. BottomRight should got up and to the left according to what it was back in Feb.

![Screen Shot 2020-08-17 at 7 57 59 AM](https://user-images.githubusercontent.com/1058725/90410613-70f76d80-e05f-11ea-8723-33ee3f1a5824.png)


If you look at commit 290c85312fca745f7d14958daa7a5e1813e90718 which is before the new changes that's not how it works in the menu nested stories. 

```
git reset --hard 290c85312fca745f7d14958daa7a5e1813e90718
npm run clean -- -y && npm run bootstrap 
cd packages/actionmenu
npm run storybook
```

**Comment by jaketrent** [comment]
@EdwardIrby I think we're saying the same thing.  What I described:

> origin=bottomRight would put the actionmenu in the bottom right and grow from there toward the top left as nested menus are expanded.

And what you described:

> BottomRight should got up and to the left according to what it was back in Feb.

Seem to be equivalent.  Your screenshot of 290c853 is correct.  I'm asserting that we need to go back to that to fix the origin=bottomRight behavior.
