### ISSUE TITLE
AppFrame<>NavCookieBanner reference implementation

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#1106]
- Update reference implementation to show frame integration with the cookie banner.
- explore using a general Portal component to render into new stacking context

**Comment by EdwardIrby** [comment]
Should we have a team CodeSandbox? Cause otherwise I would just be submitting a PR pointing to a different one for this.

https://codesandbox.io/s/psds-skills-nav-example-forked-9l5v5?file=/src/App.js

**Comment by EdwardIrby** [comment]
We already had a portal component. **createUniversalPortal**. That you can use like this:

```
import { createUniversalPortal } from "@pluralsight/ps-design-system-util";

import NavCookieBanner from "@pluralsight/ps-design-system-navcookiebanner";

import useMatchMedia from "./use-match-media";
const canUseDOM = () =>
  !!(
    typeof window !== "undefined" &&
    window.document &&
    window.document.createElement
  );
const root = canUseDOM ? document.body : null;

-------

 return (
    <AppFrame    >
      {props.children}
      {createUniversalPortal(<NavCookieBanner />, root)}
    </AppFrame>
  );
```
