### ISSUE TITLE
Skills Nav: Tweaks

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1118]
- The search input should be 40px tall
- The bounds of the vertical nav item should be 44px tall (currently they are 48px, and I probably just missed that discrepancy when I reviewed the NavItem component.  @sweeting , what does "bounds of the vert nav" mean (because I see design as 48px tall, see screenshot)?
- Put the utility button divider back

<img width="412" alt="Screen Shot 2020-08-24 at 1 10 10 PM" src="https://user-images.githubusercontent.com/552044/91085810-37000b80-e60b-11ea-9f0d-a6c4045044ca.png">

**Comment by sweeting** [comment]
@jaketrent Bullet Point 2: 44px is referring to the height of the rounded block that gets it;s background changed on hover/focus. The overall height should be 56px. 

This only applies to the vertical NavItem. That same block on the horizontal NavItem should be 40px high. I had to bump it to 44px for the vertical version to accommodate the vertical stacking of the icon and label.

![image](https://user-images.githubusercontent.com/48542/91098232-5c4a4500-e61e-11ea-8682-ed4068a58e37.png)

**Comment by jaketrent** [comment]
Brian and I jumped on a call.  Figma is showing us different things.  Looks like a tools bug.  For posterity: I am not crazy... yet.
