### ISSUE TITLE
Position: takes over ref of the show element

### ISSUE THREAD

**Issue by jwillesen** [pluralsight/design-system#1135]
## Bug

The Position component takes over the ref of its `show` property, which means the outer component can't get it.

### Expected behavior

When I pass a ref to the element I'm passing as the `show` property, I expect it to work.

### Actual behavior

Instead, the ref is never populated because it gets overridden by the Position element. See [here](https://github.com/pluralsight/design-system/blob/453fb3df126cceb24faf661d0e749e7bcb816f04/packages/position/src/react/index.js#L63
)

```jsx
  const showRef = React.useRef()
  const showEl = React.cloneElement(props.show, {
    ref: showRef,
    style: { ...props.show.props.style, ...style }
  })
```

### Steps to repro

```jsx
const myRef = useRef(null)
<Above show={<div ref={myRef}>I want a ref to this div</div>} when={isVisible}>
...
</Above>
```

myRef never gets populated.

### Related packages

- position@4.1.11

### Environment

Any

**Comment by jaketrent** [comment]
For triage: Didn't we deal with this in a similar report recently?

**Comment by jaketrent** [comment]
Perhaps related?: https://github.com/pluralsight/design-system/issues/1075

**Comment by jaketrent** [comment]
Triage: Dane will look into reproducing this error.
