### ISSUE TITLE
[datepicker]: date picker not responsive

### ISSUE THREAD

**Issue by willsoto** [pluralsight/design-system#1247]
### Expected behavior

Datepicker should not break out of its container

### Actual behavior

Datepicker breaks out of its container if it is too narrow

<img width="410" alt="Screen Shot 2020-09-28 at 2 28 44 PM" src="https://user-images.githubusercontent.com/2791730/94479274-8f926d80-01a2-11eb-8ae7-6ce8560b0213.png">

### Steps to repro

1. Put a datepicker in a container and start to make that container narrower, eventually the datepicker will break out

### Related packages

- "@pluralsight/ps-design-system-datepicker": "~7.1.5",

### Environment

- OS - MacOS 10.12
- Browser version - FF 82.0b3

**Comment by jaketrent** [comment]
Triage: Multiple inputs have min widths. Giving to design to figure if we still have min widths and, if we do, what they are.
