### ISSUE TITLE
docs: allow collapsing/hiding table of contents

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1255]
Brian, want to design this ui/interaction?

Perrrrsonally, I'm feeling cramped and then totes jeally of all this horz white space on the right margin.

<img width="1392" alt="Screen Shot 2020-09-29 at 4 10 20 PM" src="https://user-images.githubusercontent.com/552044/94621926-6b03c780-026e-11eb-8d60-be930057adbd.png">

**Comment by sweeting** [comment]
@jaketrent How about we inline the ToC at widths below this core breakpoints:
` --psBreakpointsLarge: 1280px;`

**Comment by jaketrent** [comment]
@sweeting Works for me.
