### ISSUE TITLE
docs: add links to headings

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#1281]
Add named anchors to headings and show a blue # when hovering over heading.

![image](https://user-images.githubusercontent.com/48542/94943465-fc548300-0494-11eb-837b-44c67abb61b2.png)

**Comment by jaketrent** [comment]
There are anchor names already, added when I did the TOC. Riiiight?

**Comment by sweeting** [comment]
Yeah, I guess we just need to use `cursor: pointer` to the heading styles to make it clear you can click on them.

**Comment by jaketrent** [comment]
Oh, I see.  Yeah, we should make sure they're clickable too.  👍
