### ISSUE TITLE
docs: side nav behavior

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#1320]
- All side nav sections should be collapsed by default (just restating, this should be resolved by #1318)
- The expanded/collapsed state of a section should not get reset by navigating to another page on the docs site
- Always open the section that contains the current page and make the current page nav item `active`

**Comment by jaketrent** [comment]
@sweeting Could we restate number 3 to be:

Always open and make active the section that contains the current page

The reason for this would be to cover the case of navigating not just directly via url but also via other links on the site.

**Comment by sweeting** [comment]
Here's a gif.
![Kapture 2020-10-09 at 16 57 22](https://user-images.githubusercontent.com/48542/95638011-92b61500-0a50-11eb-968e-9b54a3bd931b.gif)
