### ISSUE TITLE
prop-types: change NODE_ENV check for webpack 5

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#1327]
reported comment

> Webpack 5 remove polyfill for node global variables when targeting browser. PSDS has a usage that check the process variable, it is causing an error to be thrown in webpack 5 because the process global variable is not available anymore.
However, I am wondering if the usage of process && process.env && process.env.NODE_ENV === 'production' is necessary from the beginning as the  process.env.NODE_ENV will be string replace at 'compile' time.
Could you guys help me take a look and see if the process && process.env && process.env.NODE_ENV can be removed?

**Comment by danethurber** [comment]
suggest something more in line with the core prop-types pkg check https://github.com/facebook/prop-types/blob/master/index.js#L8

**Comment by jaketrent** [comment]
Triage: Will use just `process.env.NODE_ENV` to be compat with webpack@5.
