### ISSUE TITLE
post gitlab ci failures to slack channel

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#1371]
the slack channel is `#platform-ui-alerts`. only failures on the master branch should be reported to the slack channel

**Comment by jaketrent** [comment]
update from chris: added into channel. fine tuning. need to filter to only report on master.

**Comment by jaketrent** [comment]
Chris reports: We've done what we can. Gitlab doesn't allow tuning alerts. PR notifications also happening. (Slack is done. CI could be tuned.)

Idea: Adjust private CI to check if branch is master. If not, don't build or report or do anything.

Will do CI. Chris wants a pair. Dane will pair.

**Comment by danethurber** [comment]
digging in more I think the actually problem is coming from artifactory. i've ensured our docs deploy only build from the master branch and i'm added a delay to the build pipeline to give artifactory time to sync it's public packages. hopefully there will be less false negatives going forward
