### ISSUE TITLE
site: Tab in-app example theme setting

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#139]
### Expected behavior

Tab "in-app example" on the site should be visible in the default 'dark' region. 

### Actual behavior

![image](https://user-images.githubusercontent.com/3674406/32521392-3e5b763e-c3c8-11e7-8ee3-704d569a34ea.png)

Looks like the 'light' theme is on

**Comment by jaketrent** [comment]
Fixed. deployed.
