### ISSUE TITLE
docs: Nav - Examples need to have a dark background so they are visible when the light theme is toggled on.

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#1391]
When light theme is toggled on, the nav component examples are hard/impossible to see. Should be placed inside a container with a background of `colorsBackgroundDark[2]`.

https://design-system.pluralsight.com/components/nav

**Comment by jaketrent** [comment]
lol, awesome

**Comment by jaketrent** [comment]
orrrr, make nav light themeable

(given my DAP work this morning, this was on my mind.)
