### ISSUE TITLE
Dropdown: label not selectable using testing-library

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#1395]
using `getByLabelText` in a testing library test throws an error. testing-library is the preferred approach because it mimics user behaviour and the a11y tree. we should investigate, and update the component, to insure we are a11y compliant.

**Comment by jaketrent** [comment]
@danethurber seems like you were doing a bunch of research around this. Anything that you found that you'd like to report that might influence the way that this gets done?

**Comment by danethurber** [comment]
sure can. the best article i've found is this one -> https://www.24a11y.com/2019/select-your-poison-part-2/

the `The ARIA 1.2 combobox pattern` seems to be the best option but it does rely on a unique id for each component instance which it's great for snapshot testing(not a big deal just a hurdle).

what's interesting to me is that now all select/comboboxes/etc are using the same approach. so when we work on typeahead, multiselect, etc we might need to take different approaches
