### ISSUE TITLE
Style TAB focus state

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#14]
![bitmap](https://user-images.githubusercontent.com/3674406/27359329-0f78e43e-55d0-11e7-9a92-810baf02adac.png)

**Comment by jaketrent** [comment]
@dborodyansky do we want to have a state where the user can see that the first tab (often also the active tab) can be discerned as in-focus as well?

**Comment by jaketrent** [comment]
Committed as designed.  Please chime in on the active state question above when you can.
