### ISSUE TITLE
font: Self-host PS TT Commons

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#1410]
- Self-host the font files for PS TT Commons.
- Make allowable to request only from the following domains:
 
  - domain list is available here https://docs.google.com/document/d/1LxRaU9A2T_6cjEKykP_djmW47cfTNFb3b6Uze0VbB1o/edit#

[Font files](https://drive.google.com/file/d/19jxKWCSqHrO5D3kByeh6XubYiFR_ICqI/view?usp=sharing)

**Comment by sweeting** [comment]
@jaketrent I updated the zip with the corrected woff/woff2 files from TypeType that fix the issue in Firefox with weights not rendering correctly.

**Comment by jaketrent** [comment]
Replaced by #1459 . Closing this as dup.
