### ISSUE TITLE
font: Create a plan for the transition

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1418]
- [x] Sweets Easy: Security review
- [ ] Doc updates 
  - [ ] Jake: CDN and all that in another PR #1480 
  - [ ] Jake: Enumerate what responsibilities are included in "hosting/owning" the font files - added to PR #1480 
    - [x] What happens when cloudfront goes down? - as I think of what to write for this, the case seems different than when we had typography.com. Then, if usage was too high or payment an issue, requests would be denied. This was a business event. Now, with our font hosted on the CDN, there is no font-isolated business event that would keep the font from loading. If it's unavailable, the site is essentially unavailable. To state this in the docs seems silly. I think we skip this point.
    - [x] Where do I get the font from?
    - [x] I want to add a new domain.
- [ ] Product updates - WIP
- [x] Marketing updates - not us, being handled elsewhere
- [x] Author updates - not us, but being handled elsewhere. rolled out in 2021

**Comment by jaketrent** [comment]
We have this: https://docs.google.com/document/d/1LxRaU9A2T_6cjEKykP_djmW47cfTNFb3b6Uze0VbB1o/edit

What's left?

**Comment by jaketrent** [comment]
@sweeting , would you mind doing 2 things for this, please:

- [ ] follow up with security on their tasks and report back
- [ ] make sure the "in-progress/done" statuses in the "product transition" section of the doc are all updated

**Comment by sweeting** [comment]
Security team has signed off on the font files.
I updated the doc with as much as I know.

**Comment by jaketrent** [comment]
perfect, thank you!

**Comment by jaketrent** [comment]
btw, did some major updates to the doc this morning for sharing with devs/designers/pms post-launch what it seems like they specifically need to know at this moment.
