### ISSUE TITLE
TS: Go back and use JSX.IntrinsicElements in most places we use React.HTMLAttributes today

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1435]
- [x] Dane bits PR merged
- [x] Jake bits PR merged
- [x] Edward bits PR merged

Used consistently across the DS.

Current favorite approach:

For HTML attribute interface extensions:
```
type HTMLPropsFor<
  Tag extends keyof JSX.IntrinsicElements
> = JSX.IntrinsicElements[Tag]

... extends HTMLPropsFor<'input'>
```

For element-specific refs:
```
ref: RefFor<'input'>
```

Rationale being:

- Generics have same style
- Generic type is same, string of tagName, used internal to access a convenience map
- Use a props wrapper type because the alternative is too long (eg, `... extends React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>`)
- Use a props wrapper type because the indexed access approach does not compile (eg, `... extends JSX.IntrinsicElements['input']`)
- PropsOf becomes HTMLPropsFor, helping indicate the reason we're extending (to type check all html-native props).  Less importantly, but practically, 'PropsOf' becomes '...For' to match 'RefFor', not requiring a 'Of' vs 'For' memory on these often-related types.

This is essentially what Dane has already done in nav via the convenience types in util.  Just took me a while to come around to it. And now this is the effort to apply it consistently.

Questions:

- `RefFor` currently aliases `React.RefObject`.  We're still learning when to use `Ref`, `RefObject`, `MutableRefObject`, `RefCallback` (etc?!).  Will there come a time when this convenience wrapper breakers down and we have to use one of those specifically?  Probably. Does that hurt our convenience?  Probably not. I think will cover the common case, as far as I've seen.

History:

Convo moving away from abstractions:
https://github.com/pluralsight/design-system/pull/1419#discussion_r520797860

Convo worrying about perf of abstractions:
https://github.com/pluralsight/design-system/pull/1382#discussion_r516869756

`keyof JSX.IntrinsicElements` [large union perf problem](https://blog.andrewbran.ch/polymorphic-react-components/#distributivity-schmistributivity-im-gonna-make-it-work) we are half aware of

**Comment by danethurber** [comment]
i'm in. i'd be happy to do the refactor - should be fairly quick

**Comment by jaketrent** [comment]
I'd like to do a bit of it too.  Perhaps we can go halvsies.  And/or get Edward in on it.

**Comment by jaketrent** [comment]
Just to clarify, before we go this route, I think we should hear an "I'm in" or "I'm ___something else__" from Edward.

**Comment by EdwardIrby** [comment]
I support refactoring to use ** HTMLPropsFor && RefFor**

**Comment by jaketrent** [comment]
The proposition passes.  

I'll split the original TS list in 3.  Dane for 1/3, Jake for 2/3, Edward for 3/3, in order for voicing wanting to be involved. 🤷
