### ISSUE TITLE
docs: onboarding tooltip for site theme toggle

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#1439]
### Desired behavior

May be nice to add some sort of cue/tooltip/coach-mark to the theme toggle to help discoverability. On initial visit, and/or hover.

### Today's behavior

Super sweet toggle, but may be overlooked or not easy to locate initially. (That's just like, my opinion, man)

### The Value Add

May help users save time locating the theme functionality.

### The Tradeoffs

Not sure.

**Comment by dborodyansky** [comment]
![image](https://user-images.githubusercontent.com/3674406/98975918-96174300-24cb-11eb-9e23-088d8a6efd55.png)

**Comment by jaketrent** [comment]
I agree that it's subtle.  Also a non-traditional icon (vs, say, a sun/moon).  

We could expand it with a label or a coach-mark if the user hasn't set a cookie.

Or, it's possible, that subtle is exactly what we want this to be to our users.  For most sites, I think that subtle is a good strategy. But in this case, the theme toggle is there for a dev/designer to see what a component in the Design System looks like, toggling actively between modes.  Then, I wonder if the toggle is even located in the right place on the page.  Should it be closer to the components being showcased?  This is what v1 of docs did.  I believe v2 probably had it moved to site-level for the convenience of switching everything at once.  Not sure if our users like this better yet. Not sure they care. Haven't asked them, myself.  Dmitry is a "special" user, so I'm not sure I see this as user feedback. :D And I mean "special" in the best way.  Having made the system, you have that perspective too.

**Comment by dborodyansky** [comment]
I wouldn't classify my comment as user feedback either. I knew how to toggle theme from being aware of the design. Just a guess enhancement for consideration or dismissal. My mind did go to the coach-mark if user hasn't set a cookie as well FWIW.

**Comment by jaketrent** [comment]
^ Valuable feedback, was just trying to differentiate it from other users.  And doing it tongue-in-cheek for your comical benefit.  I hope it came across that way. :)

**Comment by dborodyansky** [comment]
Absolutely! Just agreeing with you about how special I am :)

**Comment by jaketrent** [comment]
Hey Dmitry, we chatted as a team real quick.  For now, we're thinking it's a small user base, we will have some site launch education later, and hopefully all these people will get used to it.

Closing for now.  Thanks for the input.  If we get negative feedback from users in this regard, we can revisit.
