### ISSUE TITLE
[dropdown] The shadow is no longer showing on the dropdown menu.

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#1449]
On a white background it looks like the menu items are not contained.

![image](https://user-images.githubusercontent.com/48542/99097654-28cfe480-2595-11eb-970e-388b6ceb1d05.png)

![image](https://user-images.githubusercontent.com/48542/99097708-3ab18780-2595-11eb-9f10-3c36c155a4f8.png)

**Comment by EdwardIrby** [comment]
This should be fixed without me having to do anything new due to another issue. I'm going to get the site to redeploy and see

**Comment by aj-foster** [comment]
Hello 👋🏼 is there a particular version we should upgrade to for this fix?
