### ISSUE TITLE
TS: Track and plan for changes in polymorphic types

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1453]
- [X] Inventory how we handle polymorphism currently, in what components (eg, `tagMenu` in ActionMenu and `renderContent` in Scrollable)
- [X] Record evidence of issues people have with polymorphic types that we have published

Perhaps in the future.  In a week?  See how teams use the types once they have them.

**Comment by EdwardIrby** [comment]
[Initial findings](https://docs.google.com/document/d/19PBYqBaU4x-qWFOl8jfXinqDtFMxmaScsNvh2DjXxrw/edit)

**Comment by EdwardIrby** [comment]
[Polymorphic interviews](https://docs.google.com/spreadsheets/d/1aa9F5wUkvyg_nS3PG_Zk9X5rNiaCfsdpVlsuKIlrMLM/edit#gid=0)

Recommendation: Stick with multiple props interface pattern over render props approach. Consider adopting Radix [polymorphic](https://github.com/radix-ui/primitives/tree/main/packages/react/polymorphic) & [primitive](https://github.com/radix-ui/primitives/tree/main/packages/react/primitive) in our code base for our own DX. This shouldn't change the existing experience but would allow us to offer an `as` prop for when a user wanted to change the tag type.
