### ISSUE TITLE
Dialog/Dropdown: Dropdown doesn't open when inside a dialog

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#1467]
> Hey team, we implemented a Dropdown that used ActionMenu items as its menu in the past, but since updating want to use Dropdown.Item instead.  We found that when the Dropdown is inside of a Dialog the menu never expands when clicked.  I tested and the rest of the Dialog/Form seem to be working fine.  Can you verify that this isn't just user error?
https://codesandbox.io/s/codesandboxer-example-forked-4sz1b?file=/example.tsx

https://pluralsight.slack.com/archives/C70HPSJPP/p1605736378237600

**Comment by EdwardIrby** [comment]
Cause nested createUniversalPortal calls

**Comment by EdwardIrby** [comment]
> Cause nested createUniversalPortal calls

Or not. I made a version of this [codesandbox](https://codesandbox.io/s/codesandboxer-example-forked-vttk2?file=/example.tsx) in stories for dropdown but it works as expected. So the question now is what's different. I think it might be css.

**Comment by EdwardIrby** [comment]
Looks like it's fixed by simply updating dropdown. https://codesandbox.io/s/codesandboxer-example-forked-3ut13
