### ISSUE TITLE
All packages: upgrade to React 17 (latest)

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/design-system#1470]
# Enhancement Request
React 17 comes with a few changes that help performance and linting

### The Value Add
In order to produce smaller bundles utilizing the new JSX syntax there needs to be an upgrade to Both React@latest and TS@latest using the new JSX properties in the `.tsconfig`

### The Tradeoffs
May find new linting errors in dev mode which will need to be addressed. Might not though.

**Comment by jaketrent** [comment]
Team triage: Looks like we already have peerDeps at 16.8. 17 shouldn't have breaking APIs.  Need to confirm that.  Will talk about timing when all devs are present.

**Comment by jaketrent** [comment]
Team triage: We plan to do this 1 Jan. Yeeha. Plan to be breaking change for all supporting components.

**Comment by jaketrent** [comment]
released, resolved.
