### ISSUE TITLE
@pluralsight/ps-design-system-errors: default import error (solved)

### ISSUE THREAD

**Issue by dhuddell** [pluralsight/design-system#1488]
## Bug

Component throws error if imported as default

### Expected behavior

Copy and paste PSDS snippet and work after installation

### Actual behavior

Import fails, here's the issue in the code sandbox that's link on PSDS page:
![ 2020-12-02 at 2 14 54 PM](https://user-images.githubusercontent.com/7210385/100920235-d0f80f80-34a8-11eb-91fd-04ccb3ca0694.png)

### Steps to repro

1. Import default, use component

### Fix:
(Incorrect) Default import: `import ForbiddenErrorPage from '@pluralsight/ps-design-system-errors'`
(Correct) Destructure import: `import { ForbiddenErrorPage } from '@pluralsight/ps-design-system-errors'`

I figured I would open this if you wanted to fix the snippet. 🙇

**Comment by jaketrent** [comment]
@dhuddell , thanks for the tip.  This is great.  Yes, we will fix soon.  PR in progress.  Thank you.

**Comment by jaketrent** [comment]
Confirmed shipped and fixed https://design-system.pluralsight.com/components/errors/#403-forbidden
