### ISSUE TITLE
docs: add stronger language around what needs to stay consistent in nav

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1489]
Figure out what we want to take a harder line on.  Add to the guideline bullets/etc in the docs.

**Comment by jaketrent** [comment]
@sweeting When you're done with the core type vars, is this something you're interested in picking up?  

If not, my sense is that maybe we don't know what to do here yet. I'm hoping you do. I don't. But if not, maybe we should close for now and revisit as needed when the way becomes clearer. Doesn't seem urgent at the moment. But then, this is probably a preventative measure.

**Comment by sweeting** [comment]
Yes, I will pick it up. I just need to add some additional guidelines for:

- Consistent placement of `brand`, `utility`, `user` across products with different global navigation
- Consistent design and interaction of the product switcher menu
- Brand icon visual design
