### ISSUE TITLE
Steps: new component

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1499]
**Designs**
https://www.figma.com/file/YsTklBecdddy9RZ3HXddIseD/?node-id=11787%3A47920

**Steps**
- A component that can have 2+ `Step`  components
- Can be oriented vertically or horizontally

**Step**
- 2 sizes (large, medium)
- Consists of a marker, title, optional description
- Has states for incomplete, current, completed
- Optional description is only shown when step is in the "current" state
- The number in the step marker for current/incomplete can be visible or not visible
- Can be clickable (and have a hover/active state) so you can navigate to previously completed steps

**Comment by sweeting** [comment]
Done. https://design-system.pluralsight.com/components/steps
