### ISSUE TITLE
button: clicking icon triggers onClick twice

### ISSUE THREAD

**Issue by KaidenR** [pluralsight/design-system#150]
### Expected behavior

onClick should only trigger once

### Actual behavior

When clicking the icon on the button, the onClick prop is triggered twice

The problem is that the `Btn` component is spreading all of its props over the icon component, including `onClick`

### Related packages

- button@9.5.0

### Environment

- OS - MacOS 10.12
- Browser version - Chrome v60

**Comment by jaketrent** [comment]
Great find!  I'll take a look.

**Comment by jaketrent** [comment]
@KaidenR Surprisingly, I can't reproduce this in storybook or in new unit tests or in the reference site examples.

But the reasoning for the source of the problem makes sense.

To that end, I'm going to be more specific about which props we allow into the component, which has been our strategy on later components.

For now, I'm going to allow `onClick`, `className` and `style` as usual suspects.  Are there other props ya'll are using?

**Comment by KaidenR** [comment]
Closing this since it was fixed with commit d59a019bbc3dc99c13acad1dd226a2859ea64ebb and released in 10.0.0
