### ISSUE TITLE
VerticalTabs.Tier1.Header: styleName isn't an accepted prop

### ISSUE THREAD

**Issue by izikandrw** [pluralsight/design-system#1516]
## Bug
First off, loving the new types for design system--thank you. Found a bit of an issue: the types for VerticalTabs.Tier1.Header do not allow us to pass styleName as a prop. This is just the first one we found, I imagine there are other design system components that have this issue.

### Expected behavior
I can pass styleName as a prop

### Actual behavior
1. passing styleName as a prop causes a typescript error

### Steps to repro
1. Install babel-plugin-react-css-modules library
2. Install @types/react-css-modules
3. Use VerticalTabs.Tier1.Header (and possibly other design system components) and pass it a styleName prop
4. typescript complains

### Solution
Because css-modules is a fairly common pattern in react development it would be nice if there was an update to the ps-design-system types so that any design system components allow for a styleName prop to be passed.

**Comment by danethurber** [comment]
hey @izikandrw. doing some research i've found the following. most of this is new for me so correct me if i'm wrong.

`@types/react-css-modules` is meant to be used with the `react-css-modules` package and through a HOC `styleName` is used to add the `className`

```
import React from 'react';
import CSSModules from 'react-css-modules';
import styles from './table.css';

class Table extends React.Component {
    render () {
        return <div styleName='table'>
            <div styleName='row'>
                <div styleName='cell'>A0</div>
                <div styleName='cell'>B0</div>
            </div>
        </div>;
    }
}

export default CSSModules(Table, styles);
```

Using typescript, there is also an exported typing from `@types/react-css-modules` that can also be used to inject the additional `react-css-modules` props. That type is `CSSModules.InjectedCSSModuleProps`
```
import * as React from 'react';
import CSSModules= require('react-css-modules');

const styles = {};

interface TableProps extends CSSModules.InjectedCSSModuleProps {}

class Table extends React.Component<TableProps> {
    render () {
        return <div styleName='table'>
            <div styleName='row'>
                <div styleName='cell'>A0</div>
                <div styleName='cell'>B0</div>
            </div>
        </div>;
    }
}

const TableHOC = CSSModules(Table, styles);
```

It looks like the `react-css-modules` package is now deprecated and you've upgraded to using `babel-plugin-react-css-modules` as a replacement - but that new `babel-plugin-react-css-modules` does not seem to provide typings. I've dug around and it doesn't seem like there is an official solution. There are a couple open issues for typescript support but nothing concrete.

The best advice i could give is to extend the react typing to add the `styleName` prop but your mileage may vary. Obviously an official solution from the `babel-plugin-react-css-modules` would be best - but this is where I would start.

```
// global.d.ts
import 'react';

declare module 'react' {
  interface Attributes {
    styleName?: string;
  }
}
```

I prepared an example here for you to explore https://codesandbox.io/s/adoring-ritchie-dbkf0?file=/src/index.tsx

**Comment by jaketrent** [comment]
Team triage: We probably shouldn't add the new styleName prop to support this specific solution. But for now, we hope the extended typings solution offered by dane above will be sufficient. Please reopen if that doesn't work, and we can try again to assist.
