### ISSUE TITLE
ps-design-system-util: typescript can't compile

### ISSUE THREAD

**Issue by izikandrw** [pluralsight/design-system#1518]
NOTE: We are blocked by this bug and we cannot upgrade design system components until this issue is resolved.

## Bug

When compiling a project that uses a design system component that has `ps-design-system-util` as a dependency , I get a typescript compilation error

```
../node_modules/@pluralsight/ps-design-system-util/dist/esm/use-resize-observer.d.ts:3:127 - error TS2304: Cannot find name 'ResizeObserverCallback'.

3 export declare function useResizeObserver(ref: RefObject<HTMLElement> | MutableRefObject<HTMLElement | undefined>, onResize?: ResizeObserverCallback): {
```

If I go to the file in the error above and add `import 'resize-observer-polyfill'`, it can build successfully because `ResizeObserverCallback` is imported

Since the error is occurring in a generated `.d.ts` file, I am not sure how to make the generated `.d.ts` file explicitly import the needed file that contains the `ResizeObserverCallback` type

### Expected behavior
projects using design system components that use `ps-design-system-util` build

### Actual behavior
project does not build

### Steps to repro

1. Install any ps-design-system component that uses ps-design-system-util in your project
2. Typescript compile the project

**Comment by danethurber** [comment]
hi @izikandrw i'm attempting to reproduce your issue but haven't been able to yet.

i've created a sandbox here that i'm hoping you can look at and help me out

https://codesandbox.io/s/codesandboxer-example-forked-ts5y6?file=/example.tsx

---

side note. the `resize-observer-polyfill` is a dependency of the `ps-design-system-util` package so it should have been installed along with the design system packages. can see if/where the polyfill was installed to with something like `npm ls esize-observer-polyfill`

**Comment by izikandrw** [comment]
hmmm not sure why it's not reproducible unfortunately. I remember that I got around this issue by adding `skipLibCheck": true` to my tsconfig.json. I think that made it stop trying to check types in my node_modules and let me compile. Not sure if this is the greatest solution haha. Sorry couldn't be of more help.

**Comment by danethurber** [comment]
no worries. thanks @izikandrw. I also often use `skipLibCheck` when typescript gets over zealous in it's type checking. 

closing this issue for now. please reach out if you have any other issues in the future.
