### ISSUE TITLE
Carousel:Transition bug

### ISSUE THREAD

**Issue by michaelkushlan** [pluralsight/design-system#1540]
## Instructions

On https://design-system.pluralsight.com/components/carousel#carousel the second carousel has a blip behavior when transitions. We see the same problem on our home page carousels after upgrading
The first carousel does not exhibit this behavior (only the one under the Using Portals section)

### Actual behavior

Screenshots/casts are helpful
https://user-images.githubusercontent.com/10716479/103587469-8c470600-4ea4-11eb-9eb8-e6f3d1cb72ed.mp4

### Related packages

- carousel@10.2.22

### Environment

- OS - MacOS 10.12
- Browser version - Chrome v60

**Comment by jaketrent** [comment]
By "blip", I'm observing that on the backside of the animation direction, when paging, the last carousel item will prematurely disappear.

If I remove the Toggle, blip still there.

If I modify actionBar to exclude the Position component, blip still there:

```
actionBar={[<Card.Action title="See more" icon={<MoreIcon />} />]}
```

If I remove the actionBar, this finally goes away.

**Comment by jaketrent** [comment]
After investigating this a week ago, I'm not sure where to go with it.  @EdwardIrby or @danethurber , any ideas?

**Comment by danethurber** [comment]
i'd have to dig in. initially i handled the transition states with a TransitionGroup but that maybe have stopped working throughout our refactoring
