### ISSUE TITLE
docs: Table codesandbox creation is missing a dependency

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#1545]
> Could not find dependency: 'invariant' relative to '/node_modules/@pluralsight/ps-design-system-table/dist/esm/react/index.js'

**Comment by danethurber** [comment]
i think adding `invariant` to the codesandbox deps will solve the issue

https://github.com/pluralsight/design-system/blob/master/docs/src/components/code-block/actions.tsx#L78

**Comment by jaketrent** [comment]
deployed, resolved.
