### ISSUE TITLE
font: self-host monospace

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1563]
Goal: allow same-domain browser cache

Impl idea: Other normalize, eg, normalize-monospace.css
Alt idea: Additional normalize, eg, both normalize and normalize-monospace.css

**Comment by EdwardIrby** [comment]
Could we just create font packages that a developer imports if they need a font?

**Comment by jaketrent** [comment]
^ Fine with me, Edward. I think that's the main idea with an additional normalize-monospace.css file to accompany the normalize.css that includes the normal typeface.

**Comment by jaketrent** [comment]
Brian will send Chris a font file for s3 hosting.

**Comment by sweeting** [comment]
@ps-cb Will you add these font files to our s3 bucket? [dm-mono.zip](https://github.com/pluralsight/design-system/files/6071425/dm-mono.zip)

**Comment by jaketrent** [comment]
Uploaded with John M. 

Example url: https://fonts.pluralsight.com/dm-mono/v1/dm-mono-medium-italic.ttf
