### ISSUE TITLE
[core/docs]: css var mismatch

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#1571]
mismatch with the  `--psTypeLetterSpacingAllCaps` css var. On the design-system site it says this should equal 0.08em, but it’s actually showing up as 0.8em.

**Comment by jaketrent** [comment]
dup of https://github.com/pluralsight/design-system/issues/1568

**Comment by jaketrent** [comment]
docs look fine to my eye.

**Comment by jaketrent** [comment]
@danethurber do you see this as a dup?  Do the docs look ok on second look?

If yes and yes, I think we can close. If not, please help me know what you see.

**Comment by jaketrent** [comment]
Team triage: dup, PR coming
