### ISSUE TITLE
dropdown: subsequent onChanges aren't called

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1598]
I'm having issues with the latest version of DropDown > 11.  It allows me to make one selection, but then it doesn't save any subsequent changes to the selection.  I'm seeing the same problem on the CodeSandbox example - https://codesandbox.io/s/2ruxy?module=/example.tsx.  Monday problem, but wanted to post it now so I don't forget next week!

https://pluralsight.slack.com/archives/C70HPSJPP/p1612568051061700

**Comment by EdwardIrby** [comment]
Cause is this PR #1592. Investigating why adding capture as [documented](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#fixing-potential-issues) causes failure. Pretty sure it's a DOM event lifecycle thing.
