### ISSUE TITLE
card: remove min-width and max-width from all card sizes

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#160]
## Enhancement Request

Eliminate the DS controlling min and max width on all card sizes

### Today's behavior

S, M, L Cards all have a min and a max width

### The Value Add

In practice, the arbitrary min/max don't add enough value and create compatibility issues with Layout components.

### The Tradeoffs

Users will have to be mindful about the lack of min/max defaults and create layouts accordigly

**Comment by jaketrent** [comment]
@dborodyansky This is diff than what we talked about earlier.  I think I'm fine with it.

On the site, at least, we're going to want to come up with our optimal width for our display examples.  Or we just let them go 100% width like the fully-flexible row component.

**Comment by dborodyansky** [comment]
Agreed. Optimal width for display on the site (matching symbol defaults in Sketch UI kit): 
Small: 140px;
Medium: 320px;
Large: 540px;

**Comment by jaketrent** [comment]
published in card@8.0.0
