### ISSUE TITLE
dropdown: clicking button after open does not toggle closed

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1609]
### Expected behavior

Click button to open menu. Click to close.

### Actual behavior

Click button to open menu. Click just animates it open again.

![2021-02-11 09 46 29](https://user-images.githubusercontent.com/552044/107668592-13c72800-6c4e-11eb-8e27-415f7f286eb5.gif)

@sweeting What do you think?  Is this the expected behavior?

**Comment by jaketrent** [comment]
Just verified that now it toggles closed.

**Comment by dsmyda** [comment]
It looks like this issue is back

**Comment by mdstaff** [comment]
I can reproduce this issue on the design system documentation page: https://design-system.pluralsight.com/components/dropdown

**Comment by dsmyda** [comment]
This also affects other open dropdowns on the page.

**Comment by caseybaggz** [comment]
Clicking the carrot *does* close the menu but also keeps other menus open. See #2012 

Will need to combine these behaviors.
