### ISSUE TITLE
position: losing onclick after opening a second time

### ISSUE THREAD

**Issue by AuggieH** [pluralsight/design-system#1627]
## Instructions

- fill in title: format of "<package name>: short description"
- choose: "bug" or "enhancement request" below, fill it in, and delete other section

## Bug
When using the `<ActionMenu />` component with one of the `position` React components, 
the second time you click on an `<ActionMenu.Item />` it no longer calls the function passed into `onClick`

### Expected behavior
To be able to open / close the `<ActionMenu/>`, while being rendered within a `position` component, while keeping the `onClick` functionality working.

### Actual behavior
The `onClick` function only works once.

Screenshots/casts are helpful
Link to your source code in your application repo

https://codesandbox.io/s/codesandboxer-example-forked-sqm7h?file=/example.tsx

### Steps to repro
(example in the sandbox provided above)
1. Open the `<ActionMenu />` by clicking the `<button />` with the text "click me".
2. Click the `<ActionMenu.Item />` with the text "wat"
3. Check the console to see that it logged the text "clicked"
4. repeat steps 1 - 3 and see that it doesn't log after the first time you click the `<ActionMenu.Item />`

### Debugging tips
I was able to make the `<ActionMenu/>` work while not wrapped in a `position` component.
I was also able to make the `<ActionMenu />` work while it was wrapped in a `position` component, but without an `onClose` function being passed to the `<ActionMenu />`

### Related packages

-   @pluralsight/ps-design-system-position: "^6.0.2",
-   @pluralsight/ps-design-system-actionmenu: "16.1.3",

### Environment

- OS - Linux Kernel 5.10.7
- Browser version - Firefox 84.0.2 (64-bit)

**Comment by danethurber** [comment]
double check with @AuggieH and this is no longer an issue. most likely this was fixed in https://github.com/pluralsight/design-system/pull/1611
