### ISSUE TITLE
site: add 'title' attribute guidelines to icon-only button / icon docs

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#163]
### Desired behavior

Encourage developers to add title / tooltip for non labeled buttons, so that a default browser tooltip appears on hover.

### Today's behavior

Problems/friction you encounter.

### The Value Add

Accessibility, best practices.

### The Tradeoffs

Documentation may be overlooked

**Comment by jaketrent** [comment]
Triage: Team convo on how to doc; guideline? prop?  general page?
