### ISSUE TITLE
card, row, drawer: className doesn't work on Cards, Rows, Drawers

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#164]
### Desired behavior

Ability to create css overrides for Cards, Rows, Drawers, such as other components

### Today's behavior

className doesn't work

### The Value Add

Consistent expectation and ability to modify components 

### The Tradeoffs

?

**Comment by jaketrent** [comment]
As I start thinking about this, one thing that's a challenge with these complex components is where to attach the className override.

Usually, I prefer the parent/root element.  That way, styling can be done on the app side with child selectors.

In this case, we will probably prefer that.

We also have a bunch of subcomponents that compose together to make the Card as a whole (eg, Card.Title, etc).  

We need to decide: should we put className and style overrides on each one of those as well?  Is that an expectation that we have or should make?

**Comment by jaketrent** [comment]
Triage: className is a yes; composite components are a challenge; css prop for glamor; className on subcomponents. 

Outcome: className for sure works.  Think about the other things.  Dev convo.

**Comment by EdwardIrby** [comment]
The className is being passed to the root element on the composites and the main component for these three components. Closing this issue.
