### ISSUE TITLE
[datepicker] missing peer dependencies for react-dates

### ISSUE THREAD

**Issue by willsoto** [pluralsight/design-system#1650]
### Expected behavior

I am able to install the `@pluralsight/ps-design-system-datepicker` following the instructions.* 

*Currently not documented like for other packages on the [website](https://design-system.pluralsight.com/components/datepicker) but I assume is just `npm install @pluralsight/ps-design-system-datepicker`

### Actual behavior

```
@pluralsight/ps-design-system-datepicker: react-dates@21.8.0 requires a peer of moment@^2.18.1 but none was installed.
```

This error is raised when installing using [`pnpm` and `strict-peer-dependencies`](https://pnpm.js.org/en/npmrc#strict-peer-dependencies), a feature that was also [introduced in npm 7](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies)

### Steps to repro

1.`pnpm add @pluralsight/ps-design-system-datepicker` with `strict-peer-dependencies` or `npm i @pluralsight/ps-design-system-datepicker --strict-peer-deps`

#### Solution

The solution here would be to add `moment` (along with any other peer dependencies) as a `dependency` of `@pluralsight/ps-design-system-datepicker`. According to the [docs for react-dates](https://github.com/airbnb/react-dates#install-dependencies), `moment` should be installed alongside `react-dates`.

### Related packages

- datepicker@14.0.3

### Environment

- OS - MacOS 10.12
- Browser version - N/A
- pnpm - 5.10.2
- npm - 7.6.0

**Comment by jaketrent** [comment]
Team triage: We use dayzed, not react-dates; probably just remove the dep.
