### ISSUE TITLE
[table]: missing peer dependencies

### ISSUE THREAD

**Issue by willsoto** [pluralsight/design-system#1651]
## Bug

Similar issue to #1650 

### Expected behavior

Installing `@pluralsight/ps-design-system-table` according to the documented instructions should be successful - no warnings/no errors.

### Actual behavior

When attempting to install `@pluralsight/ps-design-system-table` via the [instructions](https://design-system.pluralsight.com/components/table#usage--types), the following error is raised when using `strict-peer-deps`:

```
@pluralsight/ps-design-system-table@13.1.0 requires a peer of invariant@^2.2.4 but none was installed.
```

The additional package should either be:

1) Added as a dependency to `@pluralsight/ps-design-system-table`
2) Documented as an additional thing that needs to be installed (as is usual with `peerDependencies`)

### Steps to repro

`pnpm add @pluralsight/ps-design-system-table` with `strict-peer-dependencies`

or

`npm i @pluralsight/ps-design-system-table --strict-peer-deps`

### Related packages

- table@13.1.0

### Environment

- OS - MacOS 10.12
- Browser version - N/A
- pnpm - 5.10.2
- npm - 7.6.0

**Comment by jaketrent** [comment]
Team triage: check the suggested dep type on invariant and adjust.
