### ISSUE TITLE
[search input] [ts] enterKeyHint required but undocumented

### ISSUE THREAD

**Issue by willsoto** [pluralsight/design-system#1653]
### Expected behavior

The examples for `SearchInput` should compile when using TypeScript

### Actual behavior

A TypeScript error is raised:

```
Property 'enterKeyHint' is missing in type '{ className: string; placeholder: string; value: string; onClear: () => void; onChange: (e: ChangeEvent<HTMLInputElement>) => void; }' but required in type 'Pick<SearchInputProps, "loading" | "error" | "form" | "label" | "slot" | "style" | "title" | "pattern" | "children" | "size" | "key" | "accept" | "alt" | "autoComplete" | ... 281 more ... | "subLabel">'.ts(2741)
```

### Steps to repro

1. Load any example from the documentation in a codesandbox with TypeScript enabled. Example: https://codesandbox.io/s/v2ero?module=/example.tsx&file=/example.tsx:33-44

### Related packages

- search input@8.0.4

### Environment

- OS - MacOS 10.12
- Browser version - FF 86
- TS version - 4.0.5

**Comment by jaketrent** [comment]
Team triage: TS will suffer.  We will wiiiiiin!

**Comment by danethurber** [comment]
possibly related: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/43985

**Comment by jaketrent** [comment]
Critically, tsc works for the src itself without a problem:

```
$ tsc
$ tsc --version
Version 4.0.2
```

This seems to be a problem with codesandbox's runtime.  I'm not sure how to update that. I took a shot adding `@types/react` to the dependencies of the `docs/` project, but that doesn't seem to update the codesandbox environment. 

@danethurber or @EdwardIrby , have any alternate ideas?  If not, I'm tempted to close for now as a low-priority bug affecting only codesandbox.

**Comment by willsoto** [comment]
@jaketrent this actually occurs in my source code as well but since I repro'd in codesandbox I did not include it in the report.

**Comment by jaketrent** [comment]
@willsoto Thanks for the data point.  For you, when you run tsc, what is the output of:

```
pwd
tsc --version
```

**Comment by willsoto** [comment]
`/content-libraries/apps/client`
`4.0.5`
