### ISSUE TITLE
button: innerRef prop is being ignored

### ISSUE THREAD

**Issue by jimboslicethat** [pluralsight/design-system#166]
### Expected behavior
`Button.innerRef` should use the function passed to `props.innerRef`

### Actual behavior
`Button.innerRef` is statically set to `innerRef={el => (this.el = el)}`

It looks like this property is overwriting what the user of the component passed in. We also noticed that on line **328**, `this.props.innerRef` gets set to ref on the button anyways:
`...(this.props.innerRef ? { ref: this.props.innerRef } : {}),`

### Steps to repro

1. Pass in a custom function to Button.innerRef _(with something like a console log)_
2. Mount the component in the DOM and nothing happens.
3. Edit the package source code, removing line **353**.
4. Re-fresh the DOM and watch the magic happen.

### Related packages
n/a
### Environment
- OS - MacOS 10.12
- Browser version - Chrome v63

**Comment by jaketrent** [comment]
Fixed in #168.
