### ISSUE TITLE
searchInput: clear icon not visible and doesn't clear the input.

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#1703]
The clear icon should be visible once text has been entered in the search input and clicking it should clear the text in the input and hide the clear button again.

![CleanShot 2021-04-06 at 13 51 12](https://user-images.githubusercontent.com/48542/113770363-47b74a80-96df-11eb-8a52-b60fe2a38f83.gif)

**Comment by EdwardIrby** [comment]
It's not broken we just need to update the clear icon example on the docs to the following

```
import React from 'react'
import SearchInput from '@pluralsight/ps-design-system-searchinput'

const Comp = () => { 
  const [value, setValue] = React.useState('')
  return <SearchInput
    onClear={() => setValue('')}
    placeholder="Searching for?" 
    value={value}
    onChange={(evt: React.ChangeEvent<HTMLInputElement>) => {
      setValue(evt.target.value)
    }}
  />
}

export default Comp
```
