### ISSUE TITLE
verticaltabs: Tab navigation when collapsible

### ISSUE THREAD

**Issue by justinclary** [pluralsight/design-system#1746]
### Expected behavior

* When a collapsible vertical tab has been opened and then closed, it's children should not be able to be tabbed to

### Actual behavior

* After a collapsible vertical tab has been opened and then closed, it's children are able to be tabbed to

### Steps to repro

1. Open a collapsible vertical tab with items
2. Close the vertical tab
3. Use tab for page navigation, the child items are tabbed to before moving to top level

### Related packages

- verticaltabs@7.1.4

### Environment

- OS - MacOS 11.3 (Big Sur)
- Browser version - Chrome 90.0.4430.93

**Comment by jaketrent** [comment]
Repro'ed here: https://o2uxc.csb.app/

As mentioned, can only tab to tier1 headers at first, and this is right. Mouse over, then out. It collapses, but later tabs focus (invisibly) on the now-collapsed items.
