### ISSUE TITLE
circularprogress: resolve unique landmark problem

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1749]
Likely in linearprogress too.

Likely use progressbar and aria-valuenow
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_progressbar_role

**Comment by EdwardIrby** [comment]
@jaketrent 
We need to verify that JAWS, NVDA, Narrator support this attribute. Also there may be a use case for screenreaderonly and removing the role that treats it like a landmark. 

Recommend: Treat as image that has basic description. In sreenreaderonly simply iterate the current progress value
