### ISSUE TITLE
Select: First item is not being focused when opened

### ISSUE THREAD

**Issue by EdwardIrby** [pluralsight/design-system#1762]
When using `renderOption` or `children` the first option is not being focused when the Select opens.

**Comment by jaketrent** [comment]
Hey @EdwardIrby , when I exercise the code, I get the proper, expected results.

This [existing story, CustomRenderOption](https://github.com/pluralsight/design-system/blob/1752eb304beb22762fdf00739f39ae84fb1030a0/packages/select/src/react/__stories__/index.story.tsx#L131-L144) uses `renderOption`.

When I click the select element to open it, it opens, then I go to console and detect the focus and get the first `li`, as expected:

<img width="1120" alt="Screen Shot 2021-06-17 at 10 11 47 AM" src="https://user-images.githubusercontent.com/552044/122434574-7447d800-cf54-11eb-8cae-77fa9f3ba1b7.png">

Please help me determine if this is still a bug. Does this story contain the causal conditions for the bug? Do you have a different outcome using this story?

**Comment by jaketrent** [comment]
closing as non issue. please reopen if more evidence is uncovered for a bug.
