### ISSUE TITLE
docs: nav section isn't expanded when using search

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#1770]
When searching the docs, when you navigate to a search result, the section of the navigation containing that page isn't expanded.

Also, when hitting a component page url directly, the section containing that page is expanded, but the page isn't highlighted.

![CleanShot 2021-05-26 at 16 01 17](https://user-images.githubusercontent.com/48542/119736935-bab98380-be3b-11eb-978f-c80576bda1aa.gif)

**Comment by jaketrent** [comment]
Hey @sweeting , I can't seem to repro the error. I tried in FF, Chrome and Safari (see below). I used Enter key and mouse click to select the search result. Can you still make this happen?

![2021-06-17 10 15 26](https://user-images.githubusercontent.com/552044/122435190-051eb380-cf55-11eb-81ec-bbcc3f0e4a92.gif)

**Comment by sweeting** [comment]
@jaketrent It looks like this happens if any of the side nav sections have been manually expanded or collapsed.

Steps to reproduce:
1. Open docs site
2. Expand "Text" section
3. Search for "Button" and navigate to it from search results
4. Notice that "Text" section remains expanded and "Actions" is remains collapsed

I think the behavior should be when a page is navigated to via search results or by hitting a direct url (which may be the same thing), all other side nav sections are collapsed except the section that page is in and the nav item should be indicated as being active.

I noticed the item in the side nav isn't in the active state (blue line, higher contrast text) when you navigate to it via search results or by hitting the url directly. This happens regardless of having manually expanded/collapsed any sections.
![CleanShot 2021-06-17 at 12 49 28](https://user-images.githubusercontent.com/48542/122456166-7a48b380-cf6a-11eb-90a4-e23719a87d61.png)

**Comment by jaketrent** [comment]
Hey Brian, thanks for the sleuthing and extra detail.

Agreed:
- Nav via search or direct url, should open drawer with relevant link
- Nav link of page should have active styling

Less sure, because it's different than what we've code to date:

> all other side nav sections are collapsed except the section that page is in

Today, instead, we track all open drawers and reopen them. We store this per session. We only do this for user-clicked drawers. Again (see "Agreed" above), it seems good to open the drawer on these other events, but I'm not sure about closing the rest. It seems like a non-intuitive case, where a user's drawers stay open through clicks but then get closed on search. I'd prefer we open any new drawer on search and left the user-clicked drawers open too. Seem more intuitive. 

What are you thinking regarding this feedback?

**Comment by sweeting** [comment]
@jaketrent I agree it would be better when searching that any sections expanded remained that way as long as the section that contains the page you choose from search results is also expanded. It looked as though navigating via search was causing a page refresh, so I wasn't sure if that had something to do with Algolia.

I'd love it if the side nav didn't repaint each time you navigated to a different page, that way you wouldn't have to scroll the side nav to browse between items in a section.
![CleanShot 2021-06-17 at 13 33 46](https://user-images.githubusercontent.com/48542/122461723-f80fbd80-cf70-11eb-81b4-cae1c01b680f.gif)

Compare that to the behavior of the side nav when navigating between pages in a section on material-ui.com:
![CleanShot 2021-06-17 at 13 37 07](https://user-images.githubusercontent.com/48542/122462075-5dfc4500-cf71-11eb-9667-84764d41a799.gif)

**Comment by jaketrent** [comment]
@sweeting Check, we will keep user-clicked drawers open regardless.

Re the refresh. Yes, that's algolia. If you _click_ from page to page, like the gif in material above, you will avoid the refresh in a similar way to material's site.

**Comment by sweeting** [comment]
@jaketrent It may avoid the refresh, but it still scrolls back to the top each time you click on an item.

**Comment by jaketrent** [comment]
@sweeting Nice catch on the scroll. I'll catch that in this issue or capture in another.

**Comment by jaketrent** [comment]
Verified scroll restoration works in prod. Latest hypothesis on why would be that gatsby scroll restore was active in prod only and not local, so its values were overwriting ours. After I more completely diverged in our implementation from what was copied from gatsby, keys for sessionStorage weren't colliding.
