### ISSUE TITLE
actionmenu: undesired css prop

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1789]
Related to https://github.com/pluralsight/design-system/issues/1787

Need an approach that is comprehensive and feels like it resolves the root cause.

Need to understand how this emotion reference is making it into our code.

**Comment by EdwardIrby** [comment]
Is there an active bug this relates to? I see css in `packages/actionmenu/dist/esm/react/ellipsis.d.ts` but that also still exist on `packages/dropdown/dist/esm/react/item.d.ts`

**Comment by vkrokhin-pluralsight** [comment]
I'm facing with similar issue with https://design-system.pluralsight.com/components/radio/#radiogroup/. Should I create new issue for this ?
Version: @pluralsight/ps-design-system-radio ^10.1.10
```
Property 'css' is missing in type '{ children: Element[]; onChange: (event: any, value: any) => void; value: string; name: string; }' but required in type 'Pick<RadioGroupProps, "label" | "slot" | "style" | "title" | "name" | "className" | "color" | "id" | "lang" | "role" | "tabIndex" | "aria-activedescendant" | "aria-atomic" | ... 248 more ... | "subLabel">'.  TS2741
```

**Comment by jaketrent** [comment]
@EdwardIrby Yes, active bug. Was reported in slack. I don't have the link atm but can find if useful.

@vkrokhin-pluralsight Thanks for the extra report. Yes, this seems widespread.

**Comment by jaketrent** [comment]
Is this potentially related? https://github.com/pluralsight/design-system/pull/1667

(older, from march, not css but enterKeyHint prop)
