### ISSUE TITLE
single package: determine which components we will drop

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1795]
Introducing to the grouped stable package is a good time to deprecate some of the components that we feel aren't good fits. 

I think we might deprecate for lack of use or because of lack of _general_ use (eg, only used in a single product).

Lack of any use is the easier of the two. If we look at the latest install base, we can see the lowest number of installs.

Lack of general use is harder because if the component still has usefulness but no clear way of moving ownership, then that might have to wait. For instance, there might not be a good place for a Skills DS extension or a clear owner/maintainer, even if there was.

Once the components to deprecate are identified, we will remove them from the prerelease version of the @pluralsight/ps-design-system package.

**Comment by jaketrent** [comment]
@sweeting Would you mind taking this one and leading us in identifying the components to drop, please?

**Comment by sweeting** [comment]
Most confident about removing:
- Note: 1 Skills team using it (#dev-cat)

Used only by Skills teams, but we'll probably want to keep these until we figure out extended DSes:
- Datawell: 3 Skills teams
- Star Rating: 4 Skills teams
- Card: 8 Skills teams
- Row: 19 Skills Teams

Others with low usage to consider:
- Appframe: 4 teams (this really should be much higher)

**Comment by jaketrent** [comment]
Wow, Appframe being low is very surprising. Thanks for the research. I agree. Let's do just Note for now. 

Please close if you currently plan no further research.

**Comment by sweeting** [comment]
Closing for now
