### ISSUE TITLE
docs: create guidance for design system extension

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1799]
- [ ] Identify the guidance we want to give
- [ ] Create docs -  collab in [shared doc](https://docs.google.com/document/d/1SkqZAS5igmeqj8_qq1agGKEDrI6AOgbGS3toAD5J77A/edit?usp=sharing) first
- [x] Create starting Figma structure
- [ ] Create starting code structure

Guidance ideas:
Encouragement of sharing ui, deviations/derivatives; avoid duplication
Mean to decrease and improve decision making
Definitions - what extension is and is not, determining generality and reusability, relationship to PSDS, branding
Heads up - pitfalls to avoid, total cost of ownership
Design - figma location, naming
Implementation - typings, module, framework, organization
Publishing - naming, versioning, maintenance
Sharing - strategies, where appropriate

**Comment by sweeting** [comment]
Created a [Figma template](https://www.figma.com/file/DnFlNr8OO1hRjXac8Oiz4e/Scope-Design-System-Starting-Point) that can be used as a starting point for a design system extension.

**Comment by caseybaggz** [comment]
No longer planned for this project. Will be used in TVA. Closing.
