### ISSUE TITLE
docs: put publish in CI

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1800]
Problems:
- Patch versions on tons of packages can get noisy. Seems like sometimes versions get released that aren't needed. Lerna is "too sensitive" and perceives changes that aren't there. Or perhaps we have coupling we don't realize that updates all packages often.
- Local-machine publishing is error prone

Potential solution:
- Create CI (GH or Gitlab)-based release automation. 

What this is not:
- No new release strategy. No new package structure. Just moving `yarn publish:all` to CI. And making any adjustments to make it less noisy.

**Comment by EdwardIrby** [comment]
Document strategy or possible solution in #1969

**Comment by caseybaggz** [comment]
Since all the packages are already individually versioned and we are moving to maintenance mode, we should keep releases not using any ci to prevent version confusion any more than there already is.
