### ISSUE TITLE
docs: give changelogs sufficient detail

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1801]
Problem:
- Changelogs can lack enough detail to make them useful
- Changelogs have a lot of "empty" versions. 

Proposed solution:
- [ ] Decide what details need to be in a changelog to help a user move the next version; or work backwards to know how to write code for an older version
- [ ] Adjust changelog generation or create post-generation process for appending/editing

**Comment by EdwardIrby** [comment]
Need to suggest strategy in #1968

**Comment by caseybaggz** [comment]
Tech debt is outside the scope of maintenance. Closing.
