### ISSUE TITLE
Select/Menu: determine feature gap from ActionMenu/Dropdown

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1806]
ActionMenu vs. Menu
Dropdown vs. Select

Menu will replace ActionMenu.
Select will replace Dropdown.
Select uses Menu.

- [x] Audit the components to determine the feature deltas below

Findings:

## ActionMenu vs. Menu

- [ ] ActionMenu had ActionMenu.Icon. Menu does not. Can it put icons on items without it? Test in a new story.
- [ ] ActionMenu had nested menus. Menu does not. Only known nested menu, "Add to Channel" widget, doesn't use ActionMenu. Menu does not need nesting. Should support someone who wanted to build it.
- [ ] Menu doesn't have nested menus, but it has origin support. This doesn't seem needed without nesting. Remove.
- [ ] Other ActionMenu-Menu statics are matched.
- [ ] ActionMenu.Item was refactored to handle href?, target? and rel?. Menu hasn't. Does it need it? Test in new story.
- [ ] ActionMenu had close on click outside, resize and scroll outside. Users of Menu should do the same. Ok that it's not built in. Menu is a simpler (usually sub-) component.

## Dropdown vs. Select

- [x] Not needed. Future input change will make all dark theme input "subtle". ~Dropdown had subtle appearance. Select does not. Needs added.~
- [ ] Dropdown had label and subLabel. Select does not. Needs added.
- [ ] Dropdown was fixed for issue where scroll on menu would close it. Looks like Select may not have been. Test.
- [ ] Select has no docs page. Create it.
- [ ] Firefox Select button does not focus with tab. Does in Chrome. Another person verify, then fix.
- [ ] Dropdown tests for many items and scrolling. Select does not. Does it support it? Add a new story.

Things to verify in the Menu and Select components:
- [x] Keyboard nav - works the same in each
- [x] Install on Codesandbox and make sure usable - installed and basic usage without TS error

Finally:
- [ ] Docs referencing old components, dev options for any removed features, remove from sidenav but keep deprecated page around
- [ ] Delete the old code

**Comment by jaketrent** [comment]
Here's one: ActionMenu had nested menus. Menu does not. Do we want nested menus in Menu going forward?

**Comment by sweeting** [comment]
Doing some Menu/Select disambiguation here: 
https://www.figma.com/file/YsTklBecdddy9RZ3HXddIseD/PSDS-Web-Components?node-id=13395%3A13980

**In summary:**
A select is an input used to pick an option (or options in the case of a Multi Select) from a list of choices in a menu. We currently call this "Dropdown".
A menu is a temporary surface with a list of menu items.
Menu items can contain any kind of children (text, icon + text, checkbox + text, label+sublabel, etc.)

Borrowing heavily from:
Adobe Spectrum: [Menu](https://react-spectrum.adobe.com/react-spectrum/Menu.html) / [Picker](https://react-spectrum.adobe.com/react-spectrum/Picker.html)
Material UI: [Menu](https://material-ui.com/components/menus/) / [Select](https://material-ui.com/components/selects/)

Re: nesting: I'm not sure whether we should retain nesting. I can think of only one instance of nested menus ("Add to channel" widget), but there may be more.

**Comment by jaketrent** [comment]
"Add to Channel" nested menu does not use the DS ActionMenu.

**Comment by EdwardIrby** [comment]
#1939  work need happen first

**Comment by caseybaggz** [comment]
Tech debt is outside the scope of maintenance. Closing.
