### ISSUE TITLE
core: remove deprecated type vars

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1828]
Team question: why were we waiting to do this? Should we still wait, or has the time come?

Such as --psTypeFontSizeGigantic. On CSS and JS side.

https://github.com/pluralsight/design-system/blob/85f17aa3c8bf44f0ccfbddefd4c1971a8d6b67c9/packages/core/src/css/type.module.css#L7

**Comment by EdwardIrby** [comment]
this will be breaking @EdwardIrby  will resolve the Push part @sweeting  just needs to do the work of removing these css vars.
