### ISSUE TITLE
datepicker: make keyboard accessible

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1836]
### Expected behavior

- Tab-accessible days on the calendar
- Keyboard-openable calendar from datepicker
- More?

### Steps to repro

1. Open calendar in codesandbox, try to tab to day, can't
2. Open DS docs, try to open calendar from datepicker cal icon, can't

Notify `#dev-learner-workflow` when done.

**Comment by EdwardIrby** [comment]
Initial work done in #1933

**Comment by EdwardIrby** [comment]
Use a component interface similar to [react-datepicker](https://github.com/Hacker0x01/react-datepicker)
Follow [a11y pattern](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html)

```tsx
<DatePicker
  inline={boolean} //defaults false removes dialog role
  selected={date}
  onSelect={handleDateSelect} //when day is clicked
  onChange={handleDateChange} //only when value has changed
/>
```

## Accessibility

### Keyboard support

**Date Picker Dialog: Month/Year Buttons**

| Key	|  Function |
| ----------- | ----------- |
| Space <br> Enter | Change the month and/or year displayed in the calendar grid. |

**Date Picker Dialog: Date Grid**

| Key	|  Function |
| ----------- | ----------- |
| Space <br> Enter	| Select the date, close the dialog, and move focus to the Choose Date button. <br> Update the value of the Date input with the selected date. <br>Update the accessible name of the Choose Date button to include the selected date. |
| Up Arrow | Moves focus to the same day of the previous week. |
| Down Arrow | Moves focus to the same day of the next week.  |
| Right Arrow | Moves focus to the next day.  |
| Left Arrow | Moves focus to the previous day.  |
| Home | Moves focus to the first day (e.g Sunday) of the current week. |
| End | Moves focus to the last day (e.g. Saturday) of the current week. |
| Page Up | Changes the grid of dates to the previous month. <br> Sets focus on the same day of the same week. If that day does not exist, then moves focus to the same day of the previous or next week. |
| Shift + Page Up | Changes the grid of dates to the previous Year. <br> Sets focus on the same day of the same week. If that day does not exist, then moves focus to the same day of the previous or next week. |
| Page Down | Changes the grid of dates to the next month. <br> Sets focus on the same day of the same week. If that day does not exist, then moves focus to the same day of the previous or next week. |
| Shift + Page Down | Changes the grid of dates to the next Year. <br> Sets focus on the same day of the same week. If that day does not exist, then moves focus to the same day of the previous or next week. |
