### ISSUE TITLE
all: dashify css selectors

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1848]
We have a mix of camel case. I think we should do this before we do a breaking change release for the CSS. Get it all the same breaking change.

eg,

`.button--iconOnly`

to 

`.button--icon-only`

Would probably add this as a css refactor list item.

It's also important for us to recognize that exposing our css selectors as first class citizens will make them public api. Thus, changes to them will be breaking changes into the future. Another reason to refactor at this point.

Here's another standard that I'm creating in the PR I'm working on:

```
xLarge -> xlarge (not x-large)
xXSmall -> xxsmall (not x-x-small)
```

^ Brian will be happy. :)

Below, I'm duplicating the standard originally created in [this PR comment](https://github.com/pluralsight/design-system/pull/1870#discussion_r662471312). Hopefully it makes it more prominent and easy to find.

The Dashify standard:

1. Dashify whole words (eg, tail-position)
2. Acronomyns are not dashed (eg, svg, csv)
3. Abbreviations are not dashed (eg, xsmall, xxlarge)

**Comment by jaketrent** [comment]
Of course, this might call into question the core vars.  I'm less sure of this:

eg, should we?:

`--psTypeFontSize700`

to:

`--ps-type-font-size-700`

**Comment by EdwardIrby** [comment]
I prefer dash case always in css.

**Comment by jaketrent** [comment]
Did checks along the way in the conversion. Marking done.
