### ISSUE TITLE
text: error about glamorous-displayname not being installed

### ISSUE THREAD

**Issue by bressain** [pluralsight/design-system#185]
### Expected behavior

No errors when building via webpack

### Actual behavior

Errors when building via webpack

### Steps to repro

This was manifested through using the layout component. I suspect that the text package needs an `.npmignore` file. Might be a good idea to review other components that may suffer in the same way.

### Related packages

- layout@0.4.16

### Environment

- OS - MacOS 10.13.2
- Browser version - Chrome v63

**Comment by jaketrent** [comment]
@bressain what is the webpack error you're seeing? Would you mind pasting it here?
