### ISSUE TITLE
tag: change children propType from string to node

### ISSUE THREAD

**Issue by KaidenR** [pluralsight/design-system#188]
### Desired behavior

We need to be able to control the way the text inside a tag is ellipsified to prevent a number at the end from overflowing:

![image](https://user-images.githubusercontent.com/679346/35938616-e26f5750-0c06-11e8-9421-728626739d66.png)

We can do this pretty easily by wrapping the text in a flex container:

![image](https://user-images.githubusercontent.com/679346/35938753-5da45948-0c07-11e8-8967-048277e2a0fb.png)

But the tag complains because it requires `children` to be a string

### The Tradeoffs

Only thing I can think of is the potential for tags that don't adhere to the design standards.

**Comment by jaketrent** [comment]
I think the tradeoff that you point out is real.  We want users to only send in strings.  If we open our proptype to say something as generic as node, we're relying on users to be cognizant of the ability to now display a tag that doesn't match the styleguide.

I like how you've shown your use case could be a lot better if this was supported.

I think I'm in favor of merging your PR that addresses this.

@dborodyansky how do you like the tradeoffs?
