### ISSUE TITLE
build: upgrade to npm@latest or yarn@latest

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1884]
I would prefer npm to yarn.

Because:

- Comes with node install. Not a separate lib
- Applicable feature set is mutually similar with yarn (npm@latest includes workspaces)

Either way, running into this problem on yarn@1.22: 

https://github.com/yarnpkg/yarn/issues/7807

```
yarn install

=> error An unexpected error occurred: "expected workspace package to exist for \"babel-loader\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/jaketrent/dev/design-system/packages/icon/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error Command failed.
Exit code: 1
```

Also getting this for `yarn add` commands in packages.

Solved it with reverting to yarn@1.18: 

https://github.com/yarnpkg/yarn/issues/7807#issuecomment-588632848

```
yarn policies set-version 1.18.0
```

Feeling like yarn@1.x is dead: https://github.com/yarnpkg/yarn/issues/7734#issuecomment-819110350

**Comment by jaketrent** [comment]
Team triage: use npm@latest.

In the meantime, another potential workaround: https://github.com/lerna/lerna/tree/main/commands/add#readme

**Comment by EdwardIrby** [comment]
Need to document this in #1968 in transition internal best pracices

**Comment by caseybaggz** [comment]
NPM latest causes break in the build and testing environment. Yarn cannot be upgraded to latest because Lerna and Gatsby  do not support Yarn 2+. 😞
