### ISSUE TITLE
components: refactor to inline classNames() call

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1890]
As a part of the CSS conversion, sometimes we still use styles.fn() and sometimes we use classNames() inline. Dev team has [agreed to inline from here on out](https://github.com/pluralsight/design-system/pull/1883#discussion_r662316636). I think we should go back and make the pattern consistent where we didn't in the conversion.

**Comment by jaketrent** [comment]
Team triage: still agreed to do this.

**Comment by EdwardIrby** [comment]
Document preferred pattern and leave un-refactored for now in #1968
