### ISSUE TITLE
typeahead: re-enable broken tests

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1893]
The skipped test relate to visibility. This is going take either a visual regression solution or a solution that observes the addition and removal of class names because the actual styles are not visible to jest-dom.

**Comment by EdwardIrby** [comment]
Looks like this one is done already

**Comment by jaketrent** [comment]
Looks like these aren't re-enabled yet for typeahead:

axe-core tests: https://github.com/pluralsight/design-system/blob/8682f9716cdfa03c89fc3cb3236f19b1b00b4770/packages/typeahead/src/react/__specs__/index.spec.tsx#L41
focus test: https://github.com/pluralsight/design-system/blob/8682f9716cdfa03c89fc3cb3236f19b1b00b4770/packages/typeahead/src/react/__specs__/index.spec.tsx#L74
escape key test: https://github.com/pluralsight/design-system/blob/8682f9716cdfa03c89fc3cb3236f19b1b00b4770/packages/typeahead/src/react/__specs__/index.spec.tsx#L89

**Comment by caseybaggz** [comment]
Tech debt is outside the scope of maintanence. Closing.
