### ISSUE TITLE
menu: allow arrow keys to nav

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1900]
Prep work:
- [ ] Should a menu be keyboard navigable *in the same way* between Select, MultiSelect, TagsInput, etc.

Per Sweeting

The arrow keys can't be used to navigate the menu items.
https://www.w3.org/TR/wai-aria-practices-1.2/#menu

First reported: https://github.com/pluralsight/design-system/pull/1881#pullrequestreview-701165596

Potential help via react-aria

**Comment by Rykus0** [comment]
The menu is used to build `select`, `dropdown`, and `typeahead`.  So if keyboard navigation is added to `menu` directly then consideration for these components must be made as well.

**Comment by Rykus0** [comment]
Changing the `menu` to use keyboard navigation in the same way as the components mentioned would require a change to the API.  Plus adding the keyboard navigation to the `menu` directly would require a change to the other components which were built using it as a base, so we won't be adding this at this time.
