### ISSUE TITLE
icon: fix ''dashboard' svg and add 'tag'

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#195]
SVGs attached.

![image](https://user-images.githubusercontent.com/3674406/36560121-bbf103de-17c4-11e8-8b02-a741a5d8d064.png)
[tag-and-dashboard.zip](https://github.com/pluralsight/design-system/files/1749284/tag-and-dashboard.zip)

**Comment by jaketrent** [comment]
published in icon@8.6.0
