### ISSUE TITLE
all: find a solution for loading DS components with CSS on NextJS

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#1950]
Somehow we missed this in prep for the CSS transition. But this is a blocker for NextJS users. 

In short, our components can't import their own CSS on NextJS as of this version (11.1).

For more context, see: https://pluralsight.slack.com/archives/C70HPSJPP/p1627340844162300

Jake Set 1 (merged)

- avatar
- button
- icon

Jake Set 2 (merged)

- dialog
- textinput
- halo
- searchinput
- textarea
- circularprogress
- text

Jake Set 3 (in PR)

- actionmenu
- badge
- breadcrumb
- carousel
- card
- checkbox

Jake Set 4 (WIP) 
- datepicker
- field
- dropdown
- form
- layout

Remaining 
- appframe (scrollable dep)
- banner (text dep)
- datawell (text dep)
- drawer (row, text dep)
- emptystate (tag dep)
- errors (text dep)

Edward will work on
- linearprogress
- link
- menu
- multiselect
- navbar
- navbrand
- navcookiebanner
- navitem
- navuser
- note
- radio

Edward Set 1
- row
- screenreaderonly
- scrollable
- select
- starrating
- steps
- switch
- tab
- table
- tag
- tagsinput
- tooltip
- typeahead
- util
- verticaltabs
- viewtoggle

**Comment by jaketrent** [comment]
Potential solutions, in order of my personal desirability:

1. next.config.js workaround that allows css-loader to load global css from components imported from node_modules 
2. Separate exports in the DS for components and stylesheets separately; leave export default in tact and combined
3. Change CSS implementation; Move to CSS modules; export selector map to allow overrides from CSS-in-JS.

**Comment by jaketrent** [comment]
Attempting num 2 with this approach...

Next wants these separate:

import Button from 'button/react'
import 'button/styles.css'

(1) Move internal component css import to src/index:
import './css/index.css'
export { default } from './react/index'
export * from './vars/index'

Has to be separate all the way down (for DS component dependencies, eg, Button -> Icon)

(2) Rewrite the other internal styled DS component imports
In button/react/index.tsx:
import Icon from 'icon/react'

(3) Add *their* CSS import to src/index.tsx
import 'icon/styles.css'
import './css/index.css'
export { default } from './react/index'
export * from './vars/index'

(4) Create convenience path files to support these naming conventions
In button/:
echo "module.exports = require('./dist/cjs/react/index.js')" > react.js
echo "@import(\"./dist/cjs/css/index.css\");" > styles.css

(4a) Any package that has multiple stylesheet files will need to import all stylesheets in styles.css.
? Should the styles.css file also import dependency styles.css files? again, eg, Button -> Icon

(4b) Create matching TS definition file for react.js
cp dist/cjs/react/index.d.ts ./react.d.ts

Everyone else stay with common method of importing the default to get a styled button in one import:

import Button from 'button'

Some day, when NextJS doesn't require this, maybe we remove this as unneeded.

**Comment by EdwardIrby** [comment]
If I'm understanding you correctly in scenario 2 we don't import the css file into the tsx/ts files. Instead we do the following:
- Import a index.css file into storybook stories for visual design.
- That index.css file will import any dependent style sheets its needs like buttton/styles.css or formcontrol/styles.css into itself.
- When we build we generate a styles.css at the root of our project or dist from which as developer can import it using import `@pluralsight-design..../styles.css` to get styles for the ds component.
- This means to properly render component they'd need to import both the component and the styles.

---

Honestly I think it's the best manual solution to the problem other than just going straight css modules. However I can see some stumbling blocks on the consumer side.  What if we made a cli that they could use to do the following:
- Add component to package.json
- Update component in package.json
- create a sanitation file that imported the component with the correct css import
  - this file would also serve as a re-export for their project 
 - Once it had done any of these things prompt the user to run their chosen package install command yarn npm rushx whatevs....

**Comment by jaketrent** [comment]
Made the changes to code in num 2 in a branch:
https://github.com/pluralsight/design-system/commits/fix/nextjs

Had it working in a local app of nextjs before I ran into another normalize@6 problem. I'll get back to that after a fix to normalize and post it.

**Comment by jaketrent** [comment]
Hey @EdwardIrby , thanks for looking at this. In response,

- No, storybook should remain the same. CSS is imported at src/index.ts instead of src/react/index.tsx. Default export is still the former.
- Yes, each src/index.ts will need to import dependent styles too.
- Yes, import 'pkgName/styles.css' is the ux I want to create
- Yes, a styled component requires the .css and the .tsx file. NextJS users just have to import them in separate places. Hence this issue.
- I don't quite follow the CLI idea. What problem is it solving?

**Comment by fform** [comment]
I’m fine with the two imports. It didn’t seem like next was in a rush to change their behavior and just calling out in the docs  why you need to import separately is easy enough.

**Comment by jaketrent** [comment]
Running into issues with CSS module resolution. Not sure if it's a dependency issue or what. That's the latest guess. Effort here is starting to feel outsized for the return. Going back to look at alternative solutions in #1977.
