### ISSUE TITLE
docs: Dropdown examples have missing dependencies when opened in CodeSandbox

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#2016]
When opening any example in CodeSandbox they have missing dependencies that have to be added manually.

![CleanShot 2021-11-10 at 15 37 34](https://user-images.githubusercontent.com/48542/141205099-4e00dcb0-5ede-48cc-bc38-95646caebd57.png)

https://design-system.pluralsight.com/components/dropdown/

**Comment by caseybaggz** [comment]
duplicate of #2018 . Closing.
