### ISSUE TITLE
layout: support actions in header component

### ISSUE THREAD

**Issue by KaidenR** [pluralsight/design-system#203]
### Desired behavior

There are many page headers across the site the have some kind of button or widget to the right of the page title. The `PageHeadingLayout` component should allow you to pass in this content and render it in the right place.

Here are the pages I could find with this layout:

![image](https://user-images.githubusercontent.com/679346/38051124-96dca7de-328a-11e8-9536-6eb414bb80fe.png)
![image](https://user-images.githubusercontent.com/679346/38051651-24234b1a-328c-11e8-831f-dec01f9f18a3.png)
![image](https://user-images.githubusercontent.com/679346/38051669-329dfa46-328c-11e8-92c5-2bdd1398548a.png)
![image](https://user-images.githubusercontent.com/679346/38051162-b2ae07e6-328a-11e8-9dd2-1ebfc23f35f8.png)
![image](https://user-images.githubusercontent.com/679346/38051199-cdba34c4-328a-11e8-87ee-805c3bc2c1ae.png)
![image](https://user-images.githubusercontent.com/679346/38051213-de8530ba-328a-11e8-93d3-f97e47f807dd.png)
![image](https://user-images.githubusercontent.com/679346/38051238-eb1c38c8-328a-11e8-8e95-fe6c92a71e98.png)
![image](https://user-images.githubusercontent.com/679346/38051267-0817b07e-328b-11e8-9236-90a14a222890.png)
![image](https://user-images.githubusercontent.com/679346/38051304-200b5a6e-328b-11e8-946e-9350284fd715.png)

### The Value Add

This would allow more BCs to adopt the header component and standardize spacing without having to rethink their whole layout.

**Comment by jaketrent** [comment]
I'm all for it.  Sounds like it's something that we have on the site and want to promote through support in the Design System.  

A couple questions:

- What should we call it... "the stuff that appears in the top-right-hand corner"?
- What are the viz design specs for it?  Just spacing?  What values?  More?

**Comment by jaketrent** [comment]
@dborodyansky , when you get back, would you mind weighing in on this?

**Comment by dborodyansky** [comment]
![image](https://user-images.githubusercontent.com/3674406/38827833-08bb451c-4169-11e8-8671-244ee18e039d.png)

Agree with vertical alignment. Adding some considerations for horizontal spacing (left:0, right: large). Also suggest calling it `headingActions` or something similar.

**Comment by jaketrent** [comment]
Also, what should happen with mobile-sized viewports?  

Some specifics...

Are there title overflows (one line) or just wrap it when it runs into heading actions?  Is there a width where headingActions should go to a new line?  When wrapped, does the horz alignment change?

**Comment by dborodyansky** [comment]
![image](https://user-images.githubusercontent.com/3674406/38837929-cdd31338-4188-11e8-97ba-5bbe929f4a7e.png)

**Comment by jaketrent** [comment]
released in latest Layout package.
