### ISSUE TITLE
avatar: default 404 is really noisy

### ISSUE THREAD

**Issue by bressain** [pluralsight/design-system#204]
### Expected behavior

If there isn't an image available or whatever, use the new initials format and don't error in the console. Makes it hard to debug pages that have a lot of avatars on it.

### Actual behavior

![screen shot 2018-03-30 at 1 43 50 pm](https://user-images.githubusercontent.com/938798/38151498-c487a64c-3420-11e8-9b81-b1457025cb25.png)

### Steps to repro

1. Use the avatar component with an email that doesn't have a gravatar
2. See the error on render

### Related packages

- avatar@1.4.6

### Environment

- OS - MacOS 10.12
- Browser version - Chrome v60

**Comment by danethurber** [comment]
looks like gravatar does a redirect to the defined fallback image...maybe we could easily check if it was redirected?

parts of the app use the fallback/profile image - but we're preferring the initials correct?

**Comment by danethurber** [comment]
doesn't look like detecting the redirect is going to work

**Comment by jaketrent** [comment]
Correct, styleguide now prefers initials to the default profile image.

**Comment by danethurber** [comment]
if we use the fallback image to detect not found we can't get the new src from the dom node but we can get the images dimensions. we could render the image offscreen and if it matches the fallback image dimensions we could determine not found that way. still a shot in the dark but i like it better than comparing bytes

**Comment by jaketrent** [comment]
They both sound like lunatic solutions.... fantastic! :D
