### ISSUE TITLE
switch:input should be tabIndex="-1"

### ISSUE THREAD

**Issue by deltaepsilon** [pluralsight/design-system#212]
## Bug

I can't easily take the checkbox input within `<Switch />` out of the tab order.

### Expected behavior

I should be able to use `<Switch tabIndex="-1" />` and have that propagate down to the checkbox... or even better, the checkbox input should never get focus.

### Environment

- OS - MacOS 10.11.6
- Browser version - Chrome v66

### The Value Add

Managing tabindex is critical for accessibility.

I was able to implement a workaround for now, but it's ugly as sin and involves a bunch of manual focus management.

### The Tradeoffs

There are no tradeoffs

**Comment by jaketrent** [comment]
Released in switch @1.3.0.  See #213 for eventual approach.
