### ISSUE TITLE
action menu: animate parent menu (vertically), child menus (horizontally)

### ISSUE THREAD

**Issue by colequartootcha** [pluralsight/design-system#220]
### Desired behavior

Animate initial action menu vertically from point of origin. The animation of a nested menus would remain horizontal as is.

### Today's behavior

Un-nested action menu animates vertically and unnaturally.

### The Value Add

Polish

### The Tradeoffs

Additional logic for animation property varying whether nested or not.

**Comment by jaketrent** [comment]
Confirmed w/ Dmitry.  We are go 👍 .
