### ISSUE TITLE
searchinput: new component

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#228]
### Desired behavior

From Cole Q: "We’re going to use the text input component soon. It would be cool if there was an “x” to clear on the right side of the text box."

### Today's behavior

No X to clear text. Customization by developer would be required (possible?)

### The Value Add

Common pattern on the web, and an existing use case

### The Tradeoffs

Additional functionality and code for a subset of cases

**Comment by jaketrent** [comment]
How are we feeling about this today?  Any additional requests?  

If we want to go forward, any design thoughts related?

**Comment by dborodyansky** [comment]
@colequartootcha Would you have any additional design considerations for this?

**Comment by colequartootcha** [comment]
@dborodyansky @jaketrent some text inputs might want to support two icons. A search icon on the left and an x icon on the right. If the data the users is searching for takes a second to load I can imagine the search icon on the left becoming a loading indicator too.

**Comment by colequartootcha** [comment]
@dborodyansky The search icon isn't as crucial as the x, at least in the inline type ahead filter use case, so I feel like the search icon should be the one to change to a loading indicator when applicable.

**Comment by dborodyansky** [comment]
![image](https://user-images.githubusercontent.com/3674406/47037771-b03b9700-d134-11e8-8d86-869e8e3d6577.png)
DevStar's implementation is solid ^

**Comment by dborodyansky** [comment]
Thinking more through the intent here... I'd like to propose that this isn't as much a need to expand TextInput to support loading state and dual icons, but a need for a new standard "Search Input" component which would consist of TextInput, Loader, Button, as well as the motion details in the transition. Adding functionality to the TextInput instead would allow for same goal but could still lead to inconsistency of implementation. There is some precedent with the Breadcrumb component, which is a standard flat button but has added parameters for context. What do you think @danethurber @jaketrent ?

![image](https://user-images.githubusercontent.com/3674406/47186958-297aeb80-d2e7-11e8-98f4-a180bdfeddba.png)

**Comment by jaketrent** [comment]
Yes, I think a light composite of those other components into something new (a la Breadcrumb) makes sense to me.  

This is more clearly a win if this is a oft-used pattern (either currently or desired in the future).  If less than that, just having the building blocks for the pattern when needed might be sufficient.  And would keep clutter down.

**Comment by dborodyansky** [comment]
Design: https://www.figma.com/file/JMYh6fY0vD4MihCJ2wn3lXy6/Search-component?node-id=0%3A1
