### ISSUE TITLE
[ViewToggle] Dynamic items not rendered correctly

### ISSUE THREAD

**Issue by willsoto** [pluralsight/design-system#234]
## Bug

Version: `"@pluralsight/ps-design-system-viewtoggle": "1.3.6",`

When rendering `ViewToggle.Option`s dynamically, it seems like initial calculations are slightly off. See screenshot:

<img width="285" alt="screen shot 2018-07-16 at 3 14 05 pm" src="https://user-images.githubusercontent.com/2791730/42778402-f46a1fd6-890a-11e8-9926-51b02227203a.png">

### Expected behavior

I can render `ViewToggle.Option` dynamically and they look correct

### Actual behavior

`ViewToggle.Option` can be rendered dynamically, but it doesn't quite look right on initial render.

### Steps to repro

1. Create a `ViewToggle` component.
2. Create a list of options
3. Iterate over the list inside the `ViewToggle` creating the `Option` dynamically from the list
4. _Optional_ Set an item at index > 0 to active

For example:

```jsx
const options = ['Apple', 'Banana', 'Orange']

<ViewToggle>
  {options.map(option => {
    const active = option === 'Orange';

    return (
      <ViewToggle.Option key={option} active={active}>
        {option}
      </ViewToggle.Option>
    );
  })}
</ViewToggle>
```

### Related packages

- "@pluralsight/ps-design-system-core": "4.3.2"

### Environment

- OS - MacOS 10.13.6
- Browser version - Chrome v68

**Comment by jaketrent** [comment]
I created a storybook story that matches your example exactly and then tried some variations.  I was unable to duplicate the issue you screenshotted.  I reviewed the source code again, and I don't currently have ideas on how this might be happening.  

If you have another scenario or more details to help me approximate what you're seeing, I'd be glad to re-look at this.

**Comment by willsoto** [comment]
Thanks for trying to reproduce. 

I think I missed the root cause here, could it be the async nature of the items that cause the problem? If you simulate an ajax request (wrap a setState in a setTimeout or something to that effect), are you able to see the issue?

**Comment by jaketrent** [comment]
Good thought.  I'll give it a whirl. ^
