### ISSUE TITLE
icon: add four icons for Content Tools

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#235]
![image](https://user-images.githubusercontent.com/3674406/43221805-d0a30e92-9002-11e8-9e8a-d87e93239360.png) 
![image](https://user-images.githubusercontent.com/3674406/43339934-9fc25592-918f-11e8-925c-43f7dec6679b.png)
[svg.zip](https://github.com/pluralsight/design-system/files/2236818/svg.zip)

### Desired behavior

Add four icons.

### Today's behavior

Icons exist in design assets as part of DS, but not yet in component code

### The Value Add

Content Tools teams need to use them. Match design assets.

**Comment by jaketrent** [comment]
released
