### ISSUE TITLE
text input: restrict or discourage availability of `subtle` appearance in `dark` theme.

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#237]
Restrict or discourage availability of `subtle` appearance in `dark` theme text-input. Possibly by handling in the API and/or docs by removing the theme toggle. 

![image](https://user-images.githubusercontent.com/3674406/43543860-1ef62e20-9586-11e8-9368-21a4c309c8be.png)

**Comment by jaketrent** [comment]
Triage: remove the toggle in the docs.  Watch for if this comes up as a problem.  Could think about disabling in code then.
