### ISSUE TITLE
Action Menu: More flexibility, Support more than text

### ISSUE THREAD

**Issue by colequartootcha** [pluralsight/design-system#242]
Include if possible:
- [ ] Use new react prop type Type checker to give better warnings

### Desired behavior
Expect the action menu to support more than text and lines.

### Today's behavior
Action menu is too opinionated for about 3 use cases in the Channels bc. No support for icons, formatted text and links in action menu.

### The Value Add
More flexibility = more adoption from more teams. More consistency across action menu/dropdown things.

### The Tradeoffs
Potential misuse of the action menu if guidelines are too loose.

### Example
We're attempting to combine two different components here: text input and action menu/dropdown, but ended up using neither because of concerns about support.

![text-input-dropdown](https://user-images.githubusercontent.com/40042334/43969487-8232b802-9c87-11e8-8a1b-010bb9fd6e98.png)

**Comment by jaketrent** [comment]
Triage: divider label has come up 3x, exists in social menus today.  Will confirm and standardized the divider label look.  Will follow up on what icon and link needs there are.

**Comment by dborodyansky** [comment]
Three things here I believe from our discussions:

1) Allow for empty action menu panels (to support a channel widget, etc)
2) API support for `divider` and `divider-label` (see design below)
3) API support for `selected-item` ... we'll want to standardize this look to an icon/color

![image](https://user-images.githubusercontent.com/3674406/50118699-6854f100-0205-11e9-89ad-7cf98cc70e9c.png)

**Comment by jaketrent** [comment]
@dborodyansky I believe the state we're at on this is shopping the design proposal ^ above to the design group to come to an agreement.

**Comment by dborodyansky** [comment]
Moving "mark selection" design and discussion to #424.

What remains here...
1. `divider-label` - design complete
2. blank panel support for "channel widget in action menu" -- separate into new issue?

![image](https://user-images.githubusercontent.com/3674406/51409427-a2702600-1b16-11e9-9cbb-7639e6d4d8cd.png)

**Comment by jaketrent** [comment]
@dborodyansky re num 2, I think we can leave it here.  I think the most history we have is here.

Are you also saying that the divider w/ label is now ready to dev?

**Comment by dborodyansky** [comment]
@jaketrent yes, divider label is ready to dev.

**Comment by dborodyansky** [comment]
Updated design for reference:
https://www.figma.com/file/JImDLmaRbGWo6iWWMN1DL6nB/Select-extras?node-id=0%3A1

**Comment by jaketrent** [comment]
Related: https://github.com/pluralsight/design-system/issues/530

**Comment by jaketrent** [comment]
Triage: @sweeting  will ask about the context for this need in DS Office Hours and Product Design channel.

Questions: 
1. Who needs dividers and labels?  What for?
2. Who needs checkmarks? What for?

**Comment by jaketrent** [comment]
Triage: We never addressed this 6 mo ago in full, but it seems to not be super pertinent today, with no one asking about it.  We haven't moved on it.  Closing for now.  Please comment and/or reopen if this work would be helpful for you.
