### ISSUE TITLE
dropdown: if click outside, close dropdown

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#244]
### Desired behavior

if click outside, close dropdown
See https://pluralsight.slack.com/archives/C5CMEKH5Z/p1534272316000100

### Today's behavior

Click button or make selection to close

### The Value Add

Maybe convenient.  Would mimick how native dropdowns work.

### The Tradeoffs

Is this the UX we want?  Probably.  Can we do it reliably? Probably, but less sure.

**Comment by KaidenR** [comment]
@jaketrent We'd like to have this resolved before we use Dropdown. Would it be okay if I submitted a PR that uses an invisible page overlay to intercept clicks outside of the dropdown?
