### ISSUE TITLE
dropdown: allow initial state to be displayed

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#254]
### Desired behavior

Set value on dropdown so that the state.selectedLabel uses it initially and displays it without a user interaction.

Perhaps use ActionMenu.Item#isActive state or Dropdown#value..?

### Today's behavior

User must click an option to see anything shown.

### The Value Add

Allow for more clear data state on initial load (eg, in partial states or examples)

### The Tradeoffs

Who knows.

**Comment by jaketrent** [comment]
I just went through and dev'ed a solution where I added `defaultValue` as a prop.

Then I as I was spot-checking the other stories in the storybook, I found this one:  "placeholder, as a pre-selected item".  This brought to mind that we have support for this exact case, it was just in a way that I had forgotten.

Today, you can:

```
<Dropdown placeholder={myState.selectedValue || 'My placeholder text'} />
```

To have your `selectedValue` shown in the Dropdown on first load.

There is, obviously, a trade off here, which is that the `placeholder` is well understood to be this "in-field usage hint", but it takes a little bit of logical thinking to come to the fact that his use case is possible as well.

Options:

We could add `defaultValue`.  That is very expected because this is the _name_ of the prop used for this case in generic, controlled react components.  If we add the prop, maybe more devs find the use case support they want.  In the same breath, if we add the prop, we clutter the api just a little more leading to more learning required to use _any_ props here.

We could add something in the docs that teaches how to support this use case.  This might come in the form of this `defaultValue`<->`placeholder` synonym being pointed out in the proptype table.  Or it might be a separate paragraph mixed in somewhere.  

Both known options have their desirable points.  What other options are?  Why would you support one option over others and why?

cc @dborodyansky , @getschomp

**Comment by getschomp** [comment]
I thought about putting it in the placeholder, but I wasn't sure if the placeholder would actually be propagated on save if the user doesn't change anything and I was also unsure if that would look visually look different to the user when the value was selected (greyed out).  I'm going to play around with this strategy on the pillar dropdown and see how it behaves.  Will report back.

**Comment by jaketrent** [comment]
Hey @getschomp , thanks for the thoughts and for the future report.  

Re the save... If your save is in JavaScript, you're good to go, because that logic about what state to send to an ajax post or something is all up to you.  In other words, because the dropdown is simply a view component, the data the display and to save has to be elsewhere.  

This component doesn't currently support html form saves.  Some of the Form components do, where it was relatively straightforward.  If you need that, let us know, and we can spend cycles on it.  It's not something we've heard that people want or need at this point.

Re the viz look... The placeholder and any user-selected item should have the same look, so you're good to go there.

**Comment by jaketrent** [comment]
Triage: closing because current api supports use case.
