### ISSUE TITLE
Button: Documentation doesn't show href prop in summary

### ISSUE THREAD

**Issue by TravisBumgarner** [pluralsight/design-system#261]
## Bug

It does mention later in the documentation that you can use it but not in the props.

**Comment by jaketrent** [comment]
Triage: Yes, should be documented because creates custom behavior when present.  Still not going to include style, className, etc because they're native to html/react.

**Comment by jaketrent** [comment]
It shows `href` now.  Not sure when that happened, but I think we're good. Closing.
