### ISSUE TITLE
icon: add ability to override aria-label

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#265]
### Expected behavior

So that semantic information about what the icon is used for is apparent to a screenreader.

### Actual behavior

We have generic labels only (eg, "right arrow").  We need to allow users to override when they know more.  Beyond that, we can look at the internal usage of Icon in other DS components and make sure that we're overriding the labels helpfully once this is enabled.

### Related packages

-icon

**Comment by TravisBumgarner** [comment]
We're looking through our audit right now and came across this so I wanted to give it a 👍

**Comment by jaketrent** [comment]
Feature now supported.
