### ISSUE TITLE
table: add sticky column header row

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#270]
### Desired behavior

Prop to enable 'sticky' table header row. As seen here: https://app.pluralsight.com/plan-analytics/adventureworks/usage?dateFilter=30d&sort=members&direction=asc

### Today's behavior

No skicky header. Table header scrolls out of view.

### The Value Add

Context in longer tables.

**Comment by jaketrent** [comment]
Triage: We don't know what this will cost.  We need to play around with it. Tech discovery, and then determine if we'll do it.

**Comment by jaketrent** [comment]
Latest triage: needs design

Questions:
- How is it enabled
- Visual: gradient or no?

**Comment by jaketrent** [comment]
Design, discussed as team:

- "pin" to parent required
- No gradient

**Comment by jaketrent** [comment]
Was a part of Q2.  Teams would use it, but now we have higher priorities.  Need triage.

**Comment by jaketrent** [comment]
Triage: places that need it have already done it.  We'd love to have everyone use DS table, but there's just a pile of other stuff to do.
