### ISSUE TITLE
actionmenu: should function as a controlled component

### ISSUE THREAD

**Issue by TravisBumgarner** [pluralsight/design-system#275]
### Related packages

- actionmenu 
- dropdownmenu (Perhaps?)

### Desired behavior

There should be a prop on action menu that allows external control over which item is selected. Similar to this: 
```
 <select value={this.state.value} onChange={this.handleChange}>
            <option value="grapefruit">Grapefruit</option>
            <option value="lime">Lime</option>
            <option value="coconut">Coconut</option>
            <option value="mango">Mango</option>
          </select>
```
Found [here](https://reactjs.org/docs/forms.html#the-select-tag).

### Today's behavior

The component can't expose its state.

### The Value Add

This means that external state cannot affect the displayed option. For example, adjusting another actionmenu used as a filter wouldn't reset this one back to its initial state on change. 

### The Tradeoffs

More complex API. Otherwise, we don't see any.

**Comment by jaketrent** [comment]
Triage: We need to look at the current api and potential futures.  Plan to pair it.

**Comment by jaketrent** [comment]
`ActionMenu.Item` has an `onClick`, which will trigger an event and expose what the user has selected.  

There really isn't too much to the state of the component currently.  What it does have, it allows you to set via props.

https://design-system.pluralsight.com/components/actionmenu/

As far as I can tell, action menu is meeting its general goals of 1) getting you a reusable, consistent UI across the product, 2) being a high quality user experience, 3) enabling a good dev experience.

Controlled components are one way to solve the problem, but I hesitate to say "should".

For instance, I'm thinking about a common use case that we see ActionMenu used for: a set of links or actions to take on a piece of content like a course (eg, "remove", "add to channel", or "share on social").  Here, have a controlled value doesn't make a lot of sense to me.

And in the case where an ActionMenu is used for making a value selection, such as in our own Dropdown component (where it uses an ActionMenu internally), it seems simple enough to handle selected state for it.  See this example code: https://design-system.pluralsight.com/components/dropdown/#in-app-example

I'd love to see how the component as-is is not meeting your needs.  Maybe a link to some code, @TravisBumgarner ?

**Comment by jaketrent** [comment]
Hi Travis, following up on this stale issue:

Recently, ActionMenu now supports `value` in `ActionMenu.Item` and `onChange` in `ActionMenu`.
https://github.com/pluralsight/design-system/blob/master/packages/actionmenu/CHANGELOG.md#510-2019-07-30

And Dropdown, which uses ActionMenu does what I think is exactly what you want here, take `value` and an `onChange`, making it feel very analogous to native `<select />`. 
https://github.com/pluralsight/design-system/blob/master/packages/dropdown/CHANGELOG.md#210-2019-08-06

I hope this new api feels more natural and usable to you.  Thanks for your input!
