### ISSUE TITLE
checkbox: add partial selection state

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#282]
### Desired behavior

Via content tools team... request for partial checkbox support

### Today's behavior

only selected / deselected

### The Value Add

Common UI for table actions

![image](https://user-images.githubusercontent.com/3674406/46979212-e2da8680-d085-11e8-8b64-b62cc1f163dc.png)
![image](https://user-images.githubusercontent.com/3674406/46979220-e968fe00-d085-11e8-8d4d-cb2eec4143f9.png)

**Comment by jaketrent** [comment]
Status: closing as revisit
