### ISSUE TITLE
Info State - new pattern

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#288]
related to empty state.

Might help drive #274 in the future.

**Comment by dborodyansky** [comment]
@danethurber @jaketrent  Here is a link to design specs and docs page. Some of the illustration set assets are still outstanding, but the docs page copy and everything else is ready to go.
https://www.figma.com/file/G7IDalBuCq6llvVlwYpaEBGR/Info-states?node-id=0%3A1
