### ISSUE TITLE
form-related: focus ring not showing up

### ISSUE THREAD

**Issue by KaidenR** [pluralsight/design-system#289]
### Expected behavior

Focus ring should always show when button is focused.

### Actual behavior

When buttons are inside a container with a background, the focus ring is rendered behind the background and so does not show up. This may be an issue with all elements that have focus rings and not just button.

### Steps to repro

1. Add a button to a container that has a background.
2. Focus the button - the focus ring does not show up

**Comment by jaketrent** [comment]
Kaiden noted yesterday when talking to me about this that it's likely that ALL the form-related components are probably going to need an adjustment here.  TextInput has been fixed already ec73ec67666999412bb9cc900a8d5bda025c3ebd

**Comment by jaketrent** [comment]
This even more ready to work now that the Halo component PR has been merged.   But I'm going to wait a day to pick it up until the other jest/hoisting/touch everything PRs merge so-as to avoid being hammered at merge time.  There's other stuff to do.
