### ISSUE TITLE
<Row>: Accessibility Audit Issue with Links

### ISSUE THREAD

**Issue by TravisBumgarner** [pluralsight/design-system#347]
### Related packages

- row

### Desired behavior
I'm passing on the feedback related to the Row component from the Accessibility Audit

It's issue the issue with the A360 ID of 45 found here: https://docs.google.com/spreadsheets/d/1y0XkLieNKvjjKEsaiInriMaam3l7o1zUm3HZj_TnOSY/edit#gid=947837203

**Comment by danethurber** [comment]
from the spreadsheet

45 |   | https://app.pluralsight.com/library/search?q=ruby | Search Results | Prime |   | Each image and title in the search results | There are multiple links to the same location. | Consolidate the multiple links to the same location into a single link. | 2.4.4 | Screen Reader,Keyboard | Serious | Medium | Structure | No | https://hub.accessible360.com/issues/11770/edit |   |   |   | 9/11/18 Mark: This one is interesting. Can we not have images and titles each have the same link so if you click on either you get to the same place?

Triage: will explore a solution

**Comment by jaketrent** [comment]
Thoughts:

- Could aria-hide the row contents and include a screenreader-only version of the linked title; But that has a general use problem, where often there are other things that we want linkable: such as the author's name in the metadata line going to author profile, or the play button in the overlay going to the web player directly.
- A main use case of the Row is a Row appearing in a Drawer.  Here, it becomes important that the Row's links *specifically* clicked will trigger requests.  Clicks anywhere else on the Row in the Drawer should trigger the Drawer panel toggle.

These thoughts continue to make me wonder if it's in the best interest of the Design System to code this into the general system.

For the specific case where the search results intend to go to one location like the course page, I wonder if you might not try a specific local solution such using only plain text (no links) in the Row props and then wrapper the whole thing in your own Link tag solution.  Have you tried that already @TravisBumgarner ?  If so, how did it work or not work?  If not, what do you think about giving it a whirl?

**Comment by jaketrent** [comment]
@TravisBumgarner , would you mind chiming in on these latest thoughts and whether you think the proposed solution would work for your case? ^ Thank you.

**Comment by jaketrent** [comment]
Closing for now because I think we have a solution that's supported by the DS.  Please reopen if you're sensing something different.
