### ISSUE TITLE
starrating: half stars don't display in Safari

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#348]
### Expected behavior
All stars display, like in Chrome

### Actual behavior

![image](https://user-images.githubusercontent.com/3674406/48651928-e9745a80-e9b1-11e8-90ab-fe5dabfd9afd.png)

**Comment by TravisBumgarner** [comment]
It took me way too long to remember how to debug in Safari.

My research thus far isn't giving me anything. Will continue to look around.
