### ISSUE TITLE
@pluralsight/ps-design-system-tooltip: require content to be strings when they should be nodes

### ISSUE THREAD

**Issue by mirandaleandro** [pluralsight/design-system#349]
### Desired behavior

I believe that Tooltip - and potentially other components - is hindering the user when enforcing displayable text to be string, instead of node. 

### Today's behavior

Tooltips have been throwing this error below during development, to which we have been fine with since the component actually works given ReactNodes instead; and that in prod, the proptype checking get stripped out.
 **Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `Tooltip`, expected `string`.**

If today, an engineer working on DS decided to interact with the Tooltip content as a `string` and consider that a non-break change, we could actually materialize some issues.

### The Value Add

It's common and widely accepted that string-like content in components are typed as Nodes instead of string for their full flexibility. 
In the React world, there are many libs that deal, for instance, with I18N using Nodes, making components that receive string imcompatible-ish. 

### The Tradeoffs

Not applicable.

**Comment by danethurber** [comment]
@mirandaleandro could you try to use a `Dialog` instead of a `Tooltip` could accomplish your task. let me know if that doesn't solve your use case.

**Comment by mirandaleandro** [comment]
Same behavior happening to Table.ColumnHeader

```
Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `Table.ColumnHeader`, expected `string`.
    in Table.ColumnHeader (created by TableColumnHeader)
    in TableColumnHeader (created by AdminsTable)
    in div (created by Table.Row)
    in Table.Row (created by AdminsTable)
    in div (created by Table)
    in Table (created by AdminsTable)
    in AdminsTable (created by Admins)
    in Show (created by Admins)
    in div (created by Panel)
    in Panel (created by PanelComponent)
    in PanelComponent (created by PeoplePageLayout)
    in div (created by PeoplePageLayout)
    in div (created by Page)
    in div (created by Page)
    in Page (created by PeoplePageLayout)
    in div (created by ChromeLayout)
    in ChromeLayout (created by Styleable(ChromeLayout))
    in Styleable(ChromeLayout) (created by ChromeLayoutContainer)
    in ChromeLayoutContainer (created by Connect(ChromeLayoutContainer))
    in Connect(ChromeLayoutContainer) (created by DragDropContext(Connect(ChromeLayoutContainer)))
    in DragDropContext(Connect(ChromeLayoutContainer)) (created by PeoplePageLayout)
    in div (created by PageWithInviteModal)
    in PageWithInviteModal (created by PeoplePageLayout)
    in PeoplePageLayout (created by Admins)
    in Admins (created by Connect(Admins))
    in Connect(Admins)
    in Provider
```

**Comment by mirandaleandro** [comment]
> @mirandaleandro could you try to use a `Dialog` instead of a `Tooltip` could accomplish your task. let me know if that doesn't solve your use case.

I can check for a dialog after, thanks for the tip. But what's the reasoning behind leaving children as string type?

**Comment by nfpiche** [comment]
I'm on the same page as @mirandaleandro 

Would like to be able to pass in spans, so that styling can happen directly on that class rather than relying on knowing the built HTML from the Tooltip component so I know what child to target.

Using the dialog would certainly work, but it seems weird to use the dialog as a tooltip to get around a prop-type warning.

Tangentially, with the release of react 16.8.x (no breaking changes) we have a new way to use refs, so an update to the `innerRef` prop type would be great as well!  Rather than just a `func` ideally it would support something along the lines of `innerRef: oneOfType([func, shape({ current: element })])`.  The implementation can remain exactly the same.

lmk if you'd prefer a new issue
