### ISSUE TITLE
tab: does not support `href` attrubute

### ISSUE THREAD

**Issue by jhewlett** [pluralsight/design-system#356]
### Desired behavior

It would be great if the Tab component had support for linking to items via `href`. The way that we use the tabs, each tab represents a distinct page with its own route.

### Today's behavior

I have to use an `onClick` with a redirect. I can't do things like open in a new tab. Probably not great for screen readers, either.

### The Value Add

Things that behave like links should be links for accessibility.

### The Tradeoffs

There now needs to be logic to render tab items as either a button or a link depending on props provided.

**Comment by danethurber** [comment]
Triage: we think this is a good idea to expore
