### ISSUE TITLE
site: guideline (DO / DON'T) badge color rethink

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#358]
We should discuss how to maintain the theming and still get our guideline block badges to look as they did previously

![image](https://user-images.githubusercontent.com/3674406/49042395-eda43300-f17c-11e8-8ee9-9c94b807b4c2.png)

**Comment by dborodyansky** [comment]
Proposing this alternative to iron our the support for badge styles across themes.

![image](https://user-images.githubusercontent.com/3674406/49047736-3bc13280-f18d-11e8-9c5e-c978df7355e0.png)

Pros:
- Less limitation when stronger/subtler badges are appropriate in context.
- Alleviates the discrepancy of 'stroke' appearance not being promoted (discouraged) in light theme docs.
- Removes the possibility to use 'Stroke/Neutral' badge in the light theme, which isn't contrast compliant.

Cons:
- Renaming 'stroke' appearance to 'subtle' problematic? "Subtle" is an appearance type we use in Forms.

**Comment by jaketrent** [comment]
Fixed.
