### ISSUE TITLE
 Running test script

### ISSUE THREAD

**Issue by gitfer** [pluralsight/design-system#366]
## Running test script

Hi, I was trying to run an `npm run test` from the root folder but it (obviously?) breaks on the package-template's package.json because of the templating. 

I think that script should run all the components' test, am I right?

Should I run it in another way? I'm not sure if my question could be considered as an issue.

**Comment by gitfer** [comment]
I think it could be resolved changing the **test script** with something like `lerna run test` and configuring jest with something like `
"testPathIgnorePatterns": [
      "<rootDir>.*(create-component).*$"
    ]
` in the main package.json

If you think my solution is right, I could suggest a pull request as soon as I find time

**Comment by jaketrent** [comment]
@gitfer Yes!  This would be a great addition.  Please code up the `lerna run test` adjustment, and we'll use it.
