### ISSUE TITLE
ci: bundlesize

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#403]
track bundlesize per package

https://github.com/siddharthkp/bundlesize

**Comment by jaketrent** [comment]
some other cool ones:
https://bundlephobia.com/result?p=@pluralsight/ps-design-system-button@10.11.1
https://packagephobia.now.sh/result?p=%40pluralsight%2Fps-design-system-button
https://github.com/siddharthkp/cost-of-modules

**Comment by jaketrent** [comment]
best one for testing locally that I've found.  CLI is similar to bundlesize.  But it uses webpack to build deps and includes --why for webpack-bundle-analyzer ui.

**Comment by jaketrent** [comment]
Triage: Not high priority.  Maybe when CI changes to GH CI or something, could look at again.
