### ISSUE TITLE
all: create a plan for how to migrate along react versions

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#404]
- What apis can we use
- What are our teams using
- When will we stop supporting 15.x
- etc?

**Comment by danethurber** [comment]
triage: adding react version visibility to the Dash so we know what react versions we need to support

**Comment by jaketrent** [comment]
Got DS Dash tracking react version.  Need to take a closer look, but almost everyone tracking on react@16.x already.  Good news!

**Comment by jaketrent** [comment]
Users of old react recorded: https://github.com/pluralsight/design-system/issues/455

**Comment by jaketrent** [comment]
Have put the time period w/in Q1 2019: https://gist.github.com/jaketrent/3256f59e9200c1aa1252828ff3d4fbe2

I think we need to have a real day in that period.

And then create a policy something like:

- We'll feel free to use react@16 features after that date.
- When we tighten the supported version on a per package basis, we'll release it as a breaking change
- We won't make bug fixes to a react@15 version (almost everyone is on react@16, thus ROI on that investment is bad, we want to encourage upgrading, and our team is small)

**Comment by jaketrent** [comment]
Plan done.  We're now migrating.
