### ISSUE TITLE
util for positioning help

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#408]
- discovery
- how to market
- relates to tooltip and dialog at least

**Comment by dmcquayps** [comment]
Guides has written something for this if you care to reference. In our case, we take a targe to position relative to as well as a container used to constrain the positioning of the tooltip. We default to centering on the target, but if that makes the tooltip overflow out of the container, then we adjust. This may be too specific of an implementation for the design system.

**Comment by danethurber** [comment]
@dmcquayps send us a link and i'd love to check it out!

**Comment by jaketrent** [comment]
Cleaning up this stale ticket... we shipped this.  https://design-system.pluralsight.com/components/position/
