### ISSUE TITLE
carousel: new component

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#411]

**Comment by dborodyansky** [comment]
Design: https://www.figma.com/file/NkNv37AVyGdeCa62CEBiOtOl/DS-Carousel?node-id=0%3A1

**Comment by dborodyansky** [comment]
Design decision input doc: https://docs.google.com/document/d/1Kp1pwSNz7laU0-HD-t4VqAJvG1YyYwM01ObsJ4M36fs/edit?ts=5ce44c38#

**Comment by jaketrent** [comment]
## Design review
- S/M/L sizes on Carousel - drive the min/max on grid cells
- TODO: Brian/Dmitry - decide on S/M/L mins/maxes
- Show as many items as mins on items will allow
- Items in a carousel all the same width
- Left-aligned in grid cell
- Right-Arrow right-aligned with carousel list container
- Partial pages - use blank space, even on first page
- Transition - slide, decide easing
- Gutter - fixed
- Height determined by items, no constraints
- Gestures - likely equals a click effect; explore, maybe dev limitations

Questions
- Paging button hover/focus state, transitions?
- Smaller arrows on smaller screens?

Later (or never 🤷‍♂):  
- Paging UI - is it helpful? deal-breaker to Home for some reason?
- Multi-row pages
- Loading states
- Empty items
- Start over

Todo
- When figma updated, that's the src of truth.
