### ISSUE TITLE
avatar: insecure fallback image url

### ISSUE THREAD

**Issue by bressain** [pluralsight/design-system#417]
### Expected behavior

- Fallback image should use https instead of http

### Actual behavior

Fallback is using http which results in mixed content warnings that look especially scary in IE11 to non-devs. Seems like this is a problem with how Gravatar _prefers_ to serve up fallback images. Might need to somehow force it to use https.

Image from customer:
![image](https://user-images.githubusercontent.com/938798/50265709-056a8200-03de-11e9-8baf-31012da201bb.png)

### Steps to repro

1. Open up a channel with a member that doesn't have a gravatar (doesn't need to be the owner).
1. See the mixed content message in the console

### Related packages

- avatar@1.8.0

### Environment

- OS - MacOS 10.14.2
- All browsers

**Comment by bressain** [comment]
Looks like **we're** providing the gravatar image so its our bad. We'll change the gravatar link to send to `secure.gravatar.com`

**Comment by jimboslicethat** [comment]
Changing our url to `secure.gravatar.com` didn't seem to resolve the issue. The avatar component seems to be calling `“http://i0.wp.com/s3-us-west-2.amazonaws.com/ps-cdn/design-system/assets/transparent.gif` in version 1.8.0.

**Comment by bressain** [comment]
Been playing with this a little. To reproduce what's going on in stage/prod, put this into your browser:

https://secure.gravatar.com/avatar/00000000000000000000000000000000?r=g&s=400&d=//s3-us-west-2.amazonaws.com/ps-cdn/design-system/assets/transparent.gif

You'll see that Gravatar switches this to:

http://i0.wp.com/s3-us-west-2.amazonaws.com/ps-cdn/design-system/assets/transparent.gif

If you add https to the query:

https://secure.gravatar.com/avatar/00000000000000000000000000000000?r=g&s=400&d=https://s3-us-west-2.amazonaws.com/ps-cdn/design-system/assets/transparent.gif

You'll see that Gravatar switches to this (note the https):

https://i0.wp.com/s3-us-west-2.amazonaws.com/ps-cdn/design-system/assets/transparent.gif?ssl=1

[Looking at the Gravatar docs](https://en.gravatar.com/site/implement/images/), they're a little fuzzy on how the "protocol-agnostic" mode will work for fallback images but seems like you need to include a protocol if you want https.

Something to maybe try is to inspect the given URL and use whatever protocol it's using.

**Comment by jaketrent** [comment]
@bressain , Thanks for following up on this.  I'm trying to make sure I'm getting what you're reporting from your experimenting.  From what I'm seeing, if we always make the fallback https, we'll always get gravatar requesting an https fallback.  Is that right?  And that would be ok, right?  Seems like a good simple solution to always use https in our default fallback in the Avatar component.

**Comment by bressain** [comment]
If you feel pretty certain that we'll always want https then yeah, throw https on the fallback pixel all the time. I was uncertain of any use cases where we'd want http.
