### ISSUE TITLE
Button: Path button's text isn't vertically-centered.

### ISSUE THREAD

**Issue by rchinerman** [pluralsight/design-system#418]
## Bug

When viewing a [skill assessment](https://app.pluralsight.com/score/skill-assessment/python?context=profile), the 'Go to path' button's text isn't quite vertically-aligned.

### Expected behavior

I'd expect the text to be aligned vertically, consistent with the rest of the product.

### Actual behavior

The line-height is a few pixels off, causing it to be just a bit off-centered.

### Screenshots

![Image 1](https://i.imgur.com/Q5C83ls.png)

### Steps to repro

1. Go to a skill assessment
2. Look at button :)

### Environment

- OS - Windows 10 Pro 17134.471
- Browser version - Chrome v71.0.3578.98

**Comment by jaketrent** [comment]
Great catch.  As we've triaged, this is likely not the Design System.  We will pass this on to the corresponding product team.  Thank you!
