### ISSUE TITLE
typeahead/multiselect component

### ISSUE THREAD

**Issue by carolinapowers** [pluralsight/design-system#424]
### Desired behavior

Projects content-tools need the ability to use the PS DS dropdown component to allow authors to enter tags that belong to a specific project. The author should be able to pick a tag name from the list and see a tag added to the input field as a result of the selection. As the author picks new tags, the new tags should be added to the input field. See example below:

![image](https://user-images.githubusercontent.com/10137641/50652451-8a17dd00-0f54-11e9-9702-5a2707909ce5.png)

You can see a live example of the desired behavior at the QA page "Ask a question" modal: https://app.pluralsight.com/questions-and-answers

![image](https://user-images.githubusercontent.com/10137641/50652878-d44d8e00-0f55-11e9-8260-1cd6796362bd.png)

The dropdown used above is a custom package called `'@pluralsight/mentors-searchable-dropdown'`

The Projects team currently uses a Vue.js module to accomplish such behavior, but we would like to start using the design system dropdown component.

Here is what our current content-tools application looks like:

![image](https://user-images.githubusercontent.com/10137641/50653546-dfa1b900-0f57-11e9-893b-9dc1e234f79f.png)

### Today's behavior

Today's behavior only allow one **text** to be shown at a time. 

When trying to implement this feature, there should be known that the tags need the ability to be clickable in order to delete tags added. The way that the dropdown is currently designed, any click on it will trigger the action menu to show or hide.  

### The Value Add

As right now we can already identify two teams that need such functionality, and we believe that other teams would need it as well.

**Comment by jaredAnders** [comment]
Just came here to request this after seeing your team's demo today. Can confirm, we built something very similar for the Role IQ Manager experience and used Channels' implementation as a guideline. I can already think of another place where we're planning to use this. Would love to see something like this in the design system.

**Comment by dborodyansky** [comment]
Design proposal for consideration:

https://www.figma.com/file/JImDLmaRbGWo6iWWMN1DL6nB/Select-extras?node-id=0%3A1

**Comment by dborodyansky** [comment]
Updated design for reference:
https://www.figma.com/file/JImDLmaRbGWo6iWWMN1DL6nB/Select-extras?node-id=0%3A1

**Comment by jaketrent** [comment]
Triage: design review fresh design

**Comment by jaketrent** [comment]
Decide: 
- [ ] what name?  typeahead or other? 2 components?

**Comment by jaketrent** [comment]
Triage: We will do this 2H 2019.  

Next steps:
-1) Pick it up relatively close to the time it will be deved.
0) BrianS: Decide on component name and if it's 2 components or not
1) BrianS: UX review to thumbs up dev
2) Design review w/ dev

**Comment by sweeting** [comment]
Reviewed designs and we're good to go for dev.

**Comment by jaketrent** [comment]
Fantastico.  Thank you.  Whoever picks this up, please schedule a UX/dev design review close to the moment dev begins.

**Comment by danethurber** [comment]
notes from design review


## naming

- Select?
- is it separate from the Dropdown?
  - yes initially and reassess later

## features

- no clear all button yet
- searchable enables a textinput
- async data
  - show loading indicator
  - use downshift or roll our own autocomplete
- start with single select
  - multi select comes later
  - use Tag for multiselect
- controlled and uncontrolled values
  - onChange prop when value changes
- disabled
  - gray out
  - no focus
- menu in portal

## theme

- input supports a dark theme
- menu is always light
- subtle appearance

## keyboard

- research needed
  - delete on multiselect removes last element
- keyboard events like prism search


### API Proposal


_has all form related props (error, label, placeholder, etc)_

```jsx
<Select
  appearance={}
  defaultValue={}
  disabled
  error
  label=""
  loading
  multi
  name=""
  onChange={}
  placeholder=""
  searchable
  subLabel=""
  value={}
>
  <Select.Option label="">first</Select.Option>
  <Select.Option label="">second</Select.Option>
  <Select.Option label="">third</Select.Option>
</Select>
```

**Comment by danethurber** [comment]
some thoughts: we could build basic form building block in the form of lower level atomic components and use downshift to handle the interactions https://www.downshift-js.com/use-multiple-selection
