### ISSUE TITLE
Tab: Divider width thickens to 4px when clicking a tab in Safari

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#431]
## Bug

- In Safari, clicking a tab causes the divider to thicken to 4px (height of the selected tab border).

### Expected behavior

- The divider border would remain the same

### Actual behavior

- The divider gets thicker

Screenshots/casts are helpful
![tab border](https://user-images.githubusercontent.com/48542/50853258-fa50a500-133e-11e9-9f01-db7b7e474591.gif)

### Environment

- OS - MacOS 10.14
- Browser version - Safari 12.0.2

**Comment by jaketrent** [comment]
The thicker border was intended to be a focus indicator.  I admit it is a little odd.  And subtle enough to make you not sure if it's intended or not.  

Do alternative styles come to mind?

**Comment by dborodyansky** [comment]
@jaketrent This is actually variance in Safari vs Chrome... Chrome works as designed, but safari "tabs" focus overrides "tab" focus on click

**Comment by jaketrent** [comment]
Ah, gotcha.  Thanks for the clarification.

**Comment by danethurber** [comment]
Triage: will complete; in safari the gray border should remain small(1px tall) but does not
