### ISSUE TITLE
site: polyfill needed for ie11

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#446]
we get an error that `Object.values` can't be found. there might be others

![image_720](https://user-images.githubusercontent.com/226356/51207462-14066500-18c8-11e9-975d-43064126b905.png)

**Comment by jaketrent** [comment]
or could: https://github.com/pluralsight/design-system/pull/450/files#diff-ea2925d9b7851c0826722207d9f3a68bR84

**Comment by jaketrent** [comment]
timebox polyfill add to component

or don't use
or create util
or rely on BCs having polyfill
