### ISSUE TITLE
button: stroke appearance adds extra top 1px spacing to small and xsmall buttons

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#469]
![image](https://user-images.githubusercontent.com/3674406/52671385-cd5c5880-2ecf-11e9-8688-8c935c0334c3.png)

**Comment by jaketrent** [comment]
Attempting to repro, I see that in small and xSmall (and all other) sizes, the height is the same (good).

<img width="871" alt="Screen Shot 2019-05-08 at 3 34 06 PM" src="https://user-
images.githubusercontent.com/552044/57409950-c54a4700-71a6-11e9-9e58-6e1b30eac5c6.png">

@dborodyansky can you still repro this?  If so, will you show me where, please?

**Comment by dborodyansky** [comment]
@jaketrent  I see the occurrence on Q&A question detail screen, but certainly not in the screenshot you posted. I wonder if it is something contextual. To repro, create a Q&A question, and observe "Mark solved" button on the top right. Might be something on their end though.

**Comment by jaketrent** [comment]
This is Chrome-only.  Firefox is ok.
