### ISSUE TITLE
Icon: Add Video Icon

### ISSUE THREAD

**Issue by TravisBumgarner** [pluralsight/design-system#471]
### Desired behavior

Support for the following icon
<img width="25" alt="screen shot 2019-02-13 at 1 53 58 pm" src="https://user-images.githubusercontent.com/11890057/52736028-db28e100-2f96-11e9-8dec-a2be043a2d85.png">

### The Value Add

It will be used in new search.

**Comment by TravisBumgarner** [comment]
I'll try and add it in when I get time but that might not be for a bit.

**Comment by dborodyansky** [comment]
[icon.video.svg.zip](https://github.com/pluralsight/design-system/files/2870429/icon.video.svg.zip)
