### ISSUE TITLE
dropdown: Add max width restriction

### ISSUE THREAD

**Issue by mich8060** [pluralsight/design-system#487]
## Enhancement Request
Please add the ability to restrict the width of the dropdown to a max width.

### Desired behavior
Any text that expends past the max width should be truncated.

Support you wish you had.

### Today's behavior
Currently is you add a max width the text is extending out of the component.

### The Value Add
Designs where content sits to the right is currently being pushed right based of however long the dropdown need to be, with this enhancement we can decide how we wish to render content verses being subject to the dynamic data. 

Why this should be added/changed in the Design System. Where we could use it. Basically anywhere we have content sitting to the right of a dropdown. Right now the Home team is actively investigating implementing a design like this.

### The Tradeoffs

What we give up or deoptimize to get it. The costs.
The only trade off that I can think of is that on mobile this could cause some spacing concerns so this property should maybe not be available via the mobile phone.

**Comment by jaketrent** [comment]
@sweeting Thanks for checking that.  

Yes, I am running a Dropdown with a long option:
https://codesandbox.io/s/sharp-platform-m1yxc

And verified that it continues to grow w/o bound based on the longest menu option content.  To accomplish this design of Dropdown, Dropdown is sending style props to the ActionMenu, `{ minWidth: 0, maxWidth: 'none', width: dropdownWidth }`.
