### ISSUE TITLE
Tag: focus with onClick is grey instead of blue

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#493]
see https://pluralsight.slack.com/archives/C70HPSJPP/p1554918150006400?thread_ts=1554917021.005000&cid=C70HPSJPP

**Comment by jaketrent** [comment]
Not sure if it's a bug, but seems like it at first blush.  @dborodyansky ?

**Comment by jaketrent** [comment]
Desired state from @dborodyansky 

![tagFocusStates](https://user-images.githubusercontent.com/552044/56681561-d2374880-6686-11e9-8f3c-e0d11d123944.png)

**Comment by jaketrent** [comment]
<p>
        When is pressable (onClick or href present) and isPressed=true should be
        blue. When pressable and hovered/focused should be gray02,
        isPressed=true/false. When pressable and isPressed=false, should revert
        to normal bg of the appearance.
      </p>
Verified that ^ the above is true as-is in the code.  This problem is resolved with the removal of appearance=accent.
      <p>
        Why would you set appearance=accent (blue), because blue *only* means
        just isPressed=true (toggled on)? basic appearance => 'default'
      </p>
      <p>
        Maybe, since we're going to remove accent in a breaking change, we might
        also want to think about solving appearance=bright with Theme instead of
        an appearance. Going to do some design discovery there and hold on this.
      </p>

**Comment by jaketrent** [comment]
@dborodyansky ^ any progress on design discovery here?

**Comment by dborodyansky** [comment]
@jaketrent Some progress here: https://www.figma.com/file/LbQEN5M9hAKvY7oiS1D9T1Ox/Tag-API-v2?node-id=0%3A1 

I am liking the idea of removing `appearance` in favor of interactivity (selected) and theming. Let's discuss further.

**Comment by jaketrent** [comment]
Deployed.
