### ISSUE TITLE
icon: time duration

### ISSUE THREAD

**Issue by byumark** [pluralsight/design-system#494]
### Desired behavior

Icon to replace the clock used here...
![image](https://user-images.githubusercontent.com/5302809/56051310-67dbeb00-5d0b-11e9-87f3-3a4ba5f5f873.png)

### Today's behavior

Using 3rd party library.

### The Value Add

Using icons in the design system instead of 3rd party.

**Comment by jaketrent** [comment]
@dborodyansky what do you think?  Is this common to the app from what you've seen.

Or @byumark , what BCs do you know of that are using this icon?

**Comment by byumark** [comment]
I'm not sure if other BCs are using it. For now we've recreated it on our own, but if you decide to implement it we'll use it instead.
