### ISSUE TITLE
row: add default responsive adjustment

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#496]
### Desired behavior

As a developer, my rows adjust responsively automatically. A Medium row, appears like a small row below the breakpoint (smaller font size, w/o thumbnail)

![image](https://user-images.githubusercontent.com/3674406/56167341-ccf24380-5f8c-11e9-9e33-e6bd5deadc72.png)

### Today's behavior

No responsive

### The Value Add

Responsive default = better

### The Tradeoffs

If we adjust based on media query, we may not account for all desired use cases.

**Comment by danethurber** [comment]
let's do a couple interviews for the contexts that have rows and determine if this should be the default behaviour
