### ISSUE TITLE
row: add prop to truncate title lines

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#497]
### Desired behavior

As a developer, I can add a prop to truncate the title to a defined a number of lines. Title has ellipses for overflow text.

![image](https://user-images.githubusercontent.com/3674406/56167585-691c4a80-5f8d-11e9-92b0-13e8e14fce87.png)

### Today's behavior

Title wraps indefinitely

### The Value Add

Allows for uniformity in dense row layouts.

### The Tradeoffs

Yet another prop.

**Comment by jaketrent** [comment]
We could get rid of the "yet another prop" layout by having a set `n` for the number of lines possible.  We did this in Card: it'll wrap for 2 lines, then ellipsis.

**Comment by mich8060** [comment]
is there a way that we could get the truncation functionality extend to the Row.Text component? We are trying to wrap a single link around the row component, but we can't use the truncate prop if we don't use the Row.TextLink component inside the title prop. Doing this automatically causes an <a></a> tag to be generated inside the title, which would result in us having a link tag within a link tag (or nested link), which does not comply with the W3C or accessibility guidelines.

**Comment by jaketrent** [comment]
@mich8060 Hey Michael, thanks for asking for what your solution is needing.  I am not really sure what you're asking for.  Would you mind opening a new issue as an enhancement request and using the template there?  Most helpful would be some expected vs. actual behavior and maybe some corresponding screenshots.  Thanks!
