### ISSUE TITLE
Row.TextLink flexibility

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#506]
I have a question around the PropTypes restrictions for Row.TextLink. I am curious why this is being limited to only a tags (https://github.com/pluralsight/design-system/blob/master/packages/row/src/react/index.js#L257)? It raises an error when using custom router links, eg react-router.

https://pluralsight.slack.com/archives/C70HPSJPP/p1556285458001200

**Comment by jaketrent** [comment]
thread content: ^

issue 1

> I have a question around the PropTypes restrictions for `Row.TextLink`. I am curious why this is being limited to only `a` tags (https://github.com/pluralsight/design-system/blob/master/packages/row/src/react/index.js#L257)? It raises an error when using custom router links, eg `react-router`.

issue 2

> It also looks like it wraps whatever is provided in another anchor tag, resulting in invalid `html`?

**Comment by jaketrent** [comment]
Triaged:

Re issue 1: DS is compat with a react-router-recommended solution, see: https://design-system.pluralsight.com/components/button/#with-react-router

Re issue 2: Looked at docs for https://design-system.pluralsight.com/components/row/#metadata . HTML seems good.
