### ISSUE TITLE
ActionMenu - Json.stringify error in element-of-type.js if more than 1 ActionMenu.Item child

### ISSUE THREAD

**Issue by qheinicken** [pluralsight/design-system#512]
## Bug
![ActionMenu_Warning_stringify](https://user-images.githubusercontent.com/3373465/57332347-3672f700-70e0-11e9-8ab0-5625e8814c77.JPG)

If you have an ActionMenu that renders on pageload, you will get a Warning in console for "Failed prop type: Converting circular structure to JSON" if the ActionMenu contains more than 1 ActionMenu.Item.

### Expected behavior

No Warning.

### Actual behavior

Receive Warning upon render.

Screenshots/casts are helpful
Link to your source code in your application repo

### Steps to repro

1. Add a simple ActionMenu in App component with two ActionMenu.Item children.
2. Load app.

### Related packages

@pluralsight/ps-design-system-prop-types@2.0.0
@pluralsight/ps-design-system-actionmenu@4.1.3

### Environment

- Win10
- Browser version - Chrome v73

**Comment by jaketrent** [comment]
Thanks for the notice.  Should be fixed by #511 .
