### ISSUE TITLE
button: expose prop enumerations

### ISSUE THREAD

**Issue by iammerrick** [pluralsight/design-system#53]
Wanted to document the idea around exporting the configuration options for our components as part of the API. 

Current

```javascript
<Button
  appearance="stroke"
  size="tiny">Click me</Button>
```

Proposal

```javascript
<Button
  appearance={Button.APPEARANCES.STROKE}
  size={Button.SIZES.TINY>Click me</Button>
```
Or

```
import Button, { APPEARANCES, SIZES}   from '...'
// Splitting hairs, the point is just to make it explicit/part of the interface.
```

While this API is more characters I think it has some valuable wins...

1. More "grep-able". A developer can find all TINY buttons while doing less work (or no work) to distinguish the context.
2. Available options are explicit and part of the API itself. This enables introspection and less need to jump to the documentation. It also diminishes versioning problems where the public documentation is a different version than the component in use. 
3. For things like components knowing the magic string can in some sense be harder to guess than tooling that is made available by an API like this.
4. Typos can be caught for consumers by throwing on undefined. This could be done with the existing approach but then you would be making the options explicit which is what I'm proposing.

Happy to support if we want to continue down the current direction.

**Comment by jaketrent** [comment]
Let's try it on button first... renaming issue.
