### ISSUE TITLE
ActionMenu: ps-design-system-prop-types not found

### ISSUE THREAD

**Issue by parkerholladay** [pluralsight/design-system#533]
### Expected behavior

We can install and use the `ActionMenu` component.

### Actual behavior

```
ERROR in ./node_modules/@pluralsight/ps-design-system-actionmenu/dist/react/index.js
Module not found: Error: Can't resolve '@pluralsight/ps-design-system-prop-types' in '<repo-path>/node_modules/@pluralsight/ps-design-system-actionmenu/dist/react'
```

### Steps to repro

1. `yarn install @pluralsight/ps-design-system-actionmenu`
2. Import and use the component as described in the docs

### Related packages

- prop-types@2.0.3

**Comment by jaketrent** [comment]
Parker, thanks for taking the time to file this.  Fix pending...

**Comment by jaketrent** [comment]
repro: https://codesandbox.io/s/3d29q
