### ISSUE TITLE
TextInput: the input element has padding making it grow beyond containing div

### ISSUE THREAD

**Issue by parkerholladay** [pluralsight/design-system#535]
### Expected behavior

According to the docs the input element and its containing div should be about 40px tall

### Actual behavior

The input element is 32px wider than its containing div, and it's forcing the div to be 58px tall. This is because 8px padding is being added top and bottom, and 16px padding is added left and right. When using the `light` theme, this results in the input shrinking and growing when it is focused/unfocused. When using the `dark` theme, the blue halo just shows smaller than the input box.

[behavior-demo](https://github.com/pluralsight/design-system/files/3213951/text-input-badness.zip)

### Steps to repro

1. Use `create-react-app` to start new project
2. Add the `TextInput` component to a page
3. The input element misbehaves

### Environment

- Ubuntu 18.04 / MacOS 10.14
- Firefox 67 / Chrome 74 / Safari 12.1

**Comment by jaketrent** [comment]
Triage: Looking into this: Need to attempt a repro.

**Comment by jaketrent** [comment]
Hey Parker and everyone.  Given the age of this issue and me not being able to repro this exactly, I'm closing for now.  Reopen if you see this again, please.
