### ISSUE TITLE
xSmall Button has misaligned icon

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#544]
https://pluralsight.slack.com/archives/C70HPSJPP/p1559659312000900

example:
![image](https://user-images.githubusercontent.com/226356/58891366-9346da80-86a9-11e9-85cf-4ed1a55b64e3.png)

**Comment by jaketrent** [comment]
At this point, this seems to be from styles on the page, not the DS, see the rest of the thread in slack ^.

**Comment by jaketrent** [comment]
No further rebuttals as to the src of this problem.  Closing for now.
