### ISSUE TITLE
Add tags to small card component

### ISSUE THREAD

**Issue by mich8060** [pluralsight/design-system#549]
### Related packages
- care@10.0.1

## Enhancement Request
We would like to have the small card have the ability to display the tag on them similar to how the medium sized cards display the tag.

[https://www.figma.com/file/F9uJHgm4AOCWe5RouPFyeRSp/Small-Cards-and-Tags?node-id=0%3A1](url)

### The Value Add

Continued engagement on the homepage has time and time again shown that have a compact homepage leads to a higher retention rates.  Because of this we migrated the homepage away from the medium sized cards to the small sized card. In doing so we lost the added value of being able to differentiate content types like Interactive Courses and Projects. We feel identifying these content types if value to a users understanding that they are different from our regular course. 

### The Tradeoffs

We will definitely lose some of the image real estate, however user have let us know that those images have proved to be not helpful while selecting a piece of content to consume.

**Comment by jaketrent** [comment]
Triage: Will add tag to small Card
