### ISSUE TITLE
core: problem loading Gotham font

### ISSUE THREAD

**Issue by thujone** [pluralsight/design-system#550]
## Instructions

- fill in title: format of "<package name>: short description"
- choose: "bug" or "enhancement request" below, fill it in, and delete other section

## Bug
When I try to load Gotham at the top of my global CSS file using the suggested URL, I get a 403 error:

@import url(https://cloud.typography.com/6966154/6397212/css/fonts.css);

### Expected behavior
Download the font.

### Actual behavior
Font not downloaded.

Screenshots/casts are helpful
Link to your source code in your application repo

### Steps to repro

1. import url in global stylesheet

### Related packages

- button@7.0.1
- core@2.3.4

### Environment

- OS - MacOS 10.12
- Browser version - Chrome v60

### Desired behavior

Support you wish you had.

### Today's behavior

Problems/friction you encounter.

### The Value Add

Why this should be added/changed in the Design System. Where we could use it.

### The Tradeoffs

What we give up or deoptimize to get it. The costs.

**Comment by jaketrent** [comment]
Hey @thujone , thanks for taking notice of this.  

The typography.com url that you're referencing for the Gotham font is specifically licensed for Pluralsight.  Thus, you have to be requesting it from the pluralsight.com domain to have it load.

see: https://www.typography.com/user-guide/managing-domains

A good alternate font for Gotham would be:

https://fonts.google.com/specimen/Montserrat

Closing.

**Comment by thujone** [comment]
Thanks for the info. If you don't mind a very basic question, is the Pluralsight Design System meant for use outside of the Pluralsight domain? Or is it mostly just for Pluralsight users? What is the context that one would use Pluralsight DS?

**Comment by thujone** [comment]
Thanks for the info.
