### ISSUE TITLE
Position: Does not handle scrolling or resizing

### ISSUE THREAD

**Issue by tmonte** [pluralsight/design-system#558]
## Bug

The position component does not handle scrolling or resizing the window

### Expected behavior

The positioned element should stay attached to the target element if the window is resized or user scrolled

### Actual behavior

![position-resize](https://user-images.githubusercontent.com/1944185/59940993-71738480-9419-11e9-87cc-269e3eca9faf.gif)

### Steps to repro

1. Go to the design system documentation
2. Select the Position component
3. Resize the window

### Related packages

- position: 1.1.4

### Environment

- OS - Windows 10
- Browser version - Chrome v74

**Comment by jaketrent** [comment]
This was known and out of scope for the first version.  Part of that call was the foreseen use case, where Position is used to dynamically put elements relative to others for short amounts of time, as in the case of a tooltip or open menu.  By the time window resize might happen, the element isn't even visible.

So, I'm interested.  What is your use case for wanting this enhancement?

**Comment by jaketrent** [comment]
Closing for now.  Re-open if you feel like there's a use case for needing it.
