### ISSUE TITLE
SearchInput: light theme not working

### ISSUE THREAD

**Issue by getschomp** [pluralsight/design-system#562]
#551  Bug

### Expected behavior
Search input should be white and have the look of the light theme and be white when surrounded by the light theme component.

### Actual behavior

Black search input.

<img width="1229" alt="Screen Shot 2019-06-25 at 8 48 07 PM" src="https://user-images.githubusercontent.com/5835824/60143109-ade11080-978a-11e9-8395-e1846f7243c9.png">

### Steps to repro

Switching over a text input.  Code below:
```
        <Theme name={Theme.names.light} className={styles.searchInputContainer}>
          <SearchInput
            label="Authors"
            iconAlign={TextInput.iconAligns.right}
            placeholder="Search for author..."
            value={props.authorHandle}
            onChange={props.onAuthorSearchQueryChange}
            onKeyPress={props.onAuthorSearchEnterKeyPress}
            icon={<Icon id={Icon.ids.search} onClick={props.onAuthorSearchClick} />}
            className={styles.textInput}
            error={hasNoMenuAuthorUsers}
            subLabel={
              hasNoMenuAuthorUsers &&
              `No author's found for name or email: ${props.authorUserSearchQuery}`
            }
          />
        </Theme>
```

### Related packages

- "@pluralsight/ps-design-system-searchinput": "^1.1.2",

### Environment

- OS - MacOS 10.14.5
- Browser version - Chrome 75.0.3770.100

**Comment by jaketrent** [comment]
Triaged: For enhancement, SearchInput do everything TextInput does via props.

Re the Theme problem, that component might need upgraded.  Or there's maybe some css on the page that's causing the theme mismatch.  The docs are working fine with theme support https://design-system.pluralsight.com/components/searchinput/ @getschomp can you verify component version, please?

**Comment by jaketrent** [comment]
Splitting issue for prop support into #567.

**Comment by getschomp** [comment]
I was using 1.0 for the text input but the latest search input at the time, so maybe that is why?  feel free to close

**Comment by jaketrent** [comment]
Latest is 2.0.2.  Would you mind upgrading to it and seeing if you still have a problem, please?  https://github.com/pluralsight/design-system/blob/master/packages/textinput/CHANGELOG.md

**Comment by jaketrent** [comment]
Closing, believing resolved.  If not, please reopen.
