### ISSUE TITLE
Table color issue in new version

### ISSUE THREAD

**Issue by nouman91** [pluralsight/design-system#569]
## Instructions

- Table: Latest table version have color issues

## Bug

I have updated the table to latest version 4.0.3 and theme to latest version of 3.0.1. After doing that table colors are not what they should be. Check the screenshot for details. The version which was working 3.0.9

Screenshots/casts are helpful

### Steps to repro

1.

### Related packages

- Table@4.0.3
- Theme@3.0.1
![tablecolor](https://user-images.githubusercontent.com/17067898/60415427-9378be00-9bf4-11e9-8a0a-136b3412d7db.PNG)

**Comment by jaketrent** [comment]
Triage: will investigate.

Looks like it's text fg color and maybe border colors that are off?

We don't see this problem on the DS site atm.  Might be something in-app.  This is also getting old.  @nouman91 is this still a problem?

**Comment by danethurber** [comment]
the new theme(and related package) releases should have fix this issue.

@nouman91 please update your packages and verify
