### ISSUE TITLE
Wrong size of square keyline in iconography

### ISSUE THREAD

**Issue by FrancoBits** [pluralsight/design-system#581]
In Keyline shapes topic it's said that the square shape has a size of 16x16px. Opening the sketch file template, the square shape has 18x18px.
![image](https://user-images.githubusercontent.com/15972447/61238825-d9b13f80-a713-11e9-8034-fd6e015543ec.png)
![image](https://user-images.githubusercontent.com/15972447/61238864-edf53c80-a713-11e9-8f7d-af6e03e71b3c.png)

**Comment by jaketrent** [comment]
@sweeting Will you weigh in and help us triage this, please?

**Comment by sweeting** [comment]
@FrancoBits 18x18 is correct. We'll need to update that image in the docs. Thank you!

**Comment by jaketrent** [comment]
@sweeting Would you mind linking to the new src image here, please?

**Comment by jaketrent** [comment]
Shipped. https://design-system.pluralsight.com/patterns/iconography/
