### ISSUE TITLE
Carousel: Provide carousel metadata to children

### ISSUE THREAD

**Issue by nttibbetts** [pluralsight/design-system#595]
### Desired behavior
Provide metadata to rendered children as props, e.g.
 - position of child in current page
 - number of items per page
 - page number

### Today's behavior
Children have no way of knowing where they're rendered in the carousel

### The Value Add
This would allow us to build logic for functionality like rendering action menus on cards for the last card of a page so that a sub action menu is rendered to the left instead of the right

e.g.
![Screen Shot 2019-07-26 at 10 16 21 AM](https://user-images.githubusercontent.com/1699510/61969111-bbff9800-afa7-11e9-9a5a-4989b94f27c3.png)

### The Tradeoffs
Creates potential collisions with existing props on rendered children

**Comment by jaketrent** [comment]
Triage: will pickup

Possible solutions: hook, render prop, export context, viewport-aware position (eg, close to right edge)
