### ISSUE TITLE
Add Icon Request- Stop Recommending

### ISSUE THREAD

**Issue by manasvil** [pluralsight/design-system#599]
### The Value Add
[stop-icon.zip](https://github.com/pluralsight/design-system/files/3453731/stop-icon.zip)
<img width="43" alt="Screen Shot 2019-07-31 at 4 12 59 PM" src="https://user-images.githubusercontent.com/5871829/62244745-18025c00-b3ae-11e9-8c8b-4ceec56098e2.png">

Planning to use it consistently across multiple recs on the platform

**Comment by jaketrent** [comment]
Triage:

Hi @manasvil , thanks for the request.  At this point, we will:

- Add to figma (@sweeting )
- Recommend you use a custom SVG within your Recommendation projects https://design-system.pluralsight.com/components/icon/#custom-svg

We have a tech limitation where we're trying to avoid Icon bloat at this time.  We'll revisit the possibility of putting *all* figma icons into the React component after we address this limitation.

**Comment by manasvil** [comment]
Thanks, @jaketrent I will convey that to my devs

**Comment by sweeting** [comment]
I've added the icon to the Figma library `PSDS - Core`
