### ISSUE TITLE
date picker: support to disable date ranges

### ISSUE THREAD

**Issue by tjmabey** [pluralsight/design-system#600]
### Enhancement Request
i would like to disable dates that are in the past or after a certain date

### Desired behavior
greyed-out dates in the calendar that cannot be selected

### Today's behavior
all dates are selectable

### The Value Add
Gift of Pluralsight will allow a user to select when their gift email is delivered to the recipient. they can choose any date from date of purchase up to 90 days in the future. This change will help users select valid dates faster.

I was thinking maybe we could add two props like `disableBefore` and `disableAfter` which would accept dates in the format 'MM/DD/YYYY', and any date before or after would be greyed-out.

**Comment by jaketrent** [comment]
Triage: This is a cool feature.  We've got other high priorities.  There would be additional discovery needed around disabling dates/ranges (eg, days of the week, certain days, multiple ranges).  This is a non-trivial enhancement.  Your team has apparently found a way forward with error states on date selections outside the expected range (not ideal, but working).  

Feels like a nice to have in the future, but right now, it's going to be under a pile of things we have to do.
