### ISSUE TITLE
site: remove sketch assets

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#617]
Remove ref from site - https://design-system.pluralsight.com/design-assets/
Move "readme-images" to site src code `pluralsight/design-system/packages/site`
per BrianS;

Because sketch is out of sync; not updated

Remove from GH - https://github.com/pluralsight/design-system-assets

**Comment by jaketrent** [comment]
Do we want to delete these? https://github.com/pluralsight/design-system-assets

**Comment by sweeting** [comment]
Yes, I think we should delete the repo.
