### ISSUE TITLE
site: fix code example rendering to appropriately color following special characters such as `/`

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#64]

**Comment by jaketrent** [comment]
<img width="749" alt="screen shot 2017-08-14 at 3 32 21 pm" src="https://user-images.githubusercontent.com/552044/29292890-20217a2e-8106-11e7-8815-96d7ca73d0d0.png">

tried the other syntax highlighter built into our code editor for jsx.  it looks like this.  I like the javascript one, and I’m ok with living with some bad highlighting after some `/`.
