### ISSUE TITLE
Note: Allow Note.Action without Icon

### ISSUE THREAD

**Issue by getschomp** [pluralsight/design-system#643]
### Desired behavior

Our designer specified typography rather than an icon for the actions. 

Here is the prototype:

https://www.figma.com/proto/kLWL9s4mdCSlj7KQ9yKM78/commentsFeedback?node-id=3%3A0&viewport=-1072%2C516%2C0.5866553783416748&scaling=min-zoom

### Today's behavior

I can only specify an icon, I guess I could hide the icon?

### The Value Add

We would use it in assessment tooling.

### The Tradeoffs

The prop would take more types, complicating things.  Could we have it take Node[] rather than just an icon incase we want to apply styles etc.?

**Comment by jaketrent** [comment]
@sweeting , will you triage this w/ the team, please?

**Comment by jaketrent** [comment]
Triage:  Discovery needed to decide how to address this.  @sweeting is handling.

Eg... Potential move toward action area, open layout.  Or move toward some more control in various subcomponents.  Or even some re-layout with avatar alignment.  Or even some actionArea (non) movement.

**Comment by jaketrent** [comment]
Wow, this needs a bump.  @sweeting will you help us triage what we want to do on this,  please?

**Comment by jaketrent** [comment]
Team triage: One team uses. This is old. We'll close for now.
