### ISSUE TITLE
Button: esm build

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#654]
Desired outcome: 
- esm allows app tooling to tree shake for smaller bundle sizes (ie, don't include icons not used from the Icon package)
- esm build alongside cjs (non-breaking change, cjs users can continue)

To verify outcomes:
- Publish esm build of Icon
- Conduct live CPT interviews with devs who use DS to see how they like our solution

Next step after this first issue:
- Probably, Button esm build
- For outcome: *internal* bundles smaller, tree-shaken (ie, Button package doesn't include entire Icon package)
- Then, later: *all* DS packages can say the same for subdependencies

Potential solutions:
- Outcome is more important, but would love to see minimal tooling (if possible, no adds); Maybe that's possible with a babel-plugin;  But maybe that's not;  Or maybe introducing something like Rollup is actually simpler than what we have.  Simpler would be a great reason to change tooling.
- Keeping module import usage the same is a plus, but it might not be possible.

**Comment by EdwardIrby** [comment]
Do we want our modules to transpile JSX or leave that up to devs build/bundle process?

**Comment by jaketrent** [comment]
Yes, I think we want to babel down to es5 (or more precisely, probably the current browserlist).  This will allow teams to not have to do any additional setup in their module loader config to process our modules.

**Comment by EdwardIrby** [comment]
Updating to show switch to Button for this OKR
