### ISSUE TITLE
tab: add option for manual activation of tab content

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#658]
Currently using arrow keys for keyboard navigation in the tab component automatically changes the tab contents when the tab gains focus. For some of our tabs in the product this might cause a refresh of the page which would cause the loss of focus and not be very usable with a keyboard.

We should add the ability to manually change the tab content with the enter key where the tab content is not loaded automatically when the tab gets focus.

- [ ] Design the focus (but not selected) state for a tab
- [ ] Dev work
- [ ] Add documentation for when to use automatic or manual tab content loading to docs.

**Comment by jaketrent** [comment]
Triage: This is a docs-only fix. 

Even if we go manual tab switching, we still will have a UX problem. Page refreshes, focus *needs* to go to the next tab list item.  DS can't do this.  It's going to be an app developer putting the refocus into app code.  Does DS provide instructions/guidelines for this?  Or simply state that this is a responsibility of Tab users that have tab content across URLs.

**Comment by EdwardIrby** [comment]
For now this a responsibility of the tab user. Those using this who wish to make refocusing work will need to write their tab set without the use of array methods. This may be a not be desirable by some teams. 

There is no way to use the composite component as it is with a dynamic Array.map based approach, do the use of `cloneElement` inside the the component in my opinion. I'd recommend rebuilding this component in the future maybe H2 and seperating interaction from structure ala [downshift](https://github.com/downshift-js/downshift).
