### ISSUE TITLE
table: responsive/touch support

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#662]
Next step: design

Ideas: scrollbar on small screen

**Comment by sweeting** [comment]
Here's a Figma [design](https://www.figma.com/file/bFde3EtBJrBQKRlIoA2PyV/Table-Responsive-w-Sticky-Header?node-id=5%3A669) and [prototype](https://www.figma.com/proto/bFde3EtBJrBQKRlIoA2PyV/Table-Responsive-w-Sticky-Header?node-id=5%3A669&viewport=277%2C675%2C0.5&scaling=min-zoom) for responsive tables and sticky headers. Responsive isn't dependent on sticky headers, but I included it in case it informs how we do the responsive part.

**Comment by sweeting** [comment]
Here are some reference examples of [a responsive table](https://codesandbox.io/s/74luo) and [a responsive table with sticky header](https://codesandbox.io/s/huoee) from Material UI.

**Comment by jaketrent** [comment]
Latest PR with small screen scroll is good-as-done. Closing.
