### ISSUE TITLE
TagMenu: new component

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#669]

**Comment by danethurber** [comment]
concerns around design and appropriateness of additional to the core design system

**Comment by jaketrent** [comment]
Hmm, What is a TagMenu?

**Comment by danethurber** [comment]
it's what i was calling this thing....

<img width="1435" alt="Screen Shot 2019-09-25 at 9 56 58 AM" src="https://user-images.githubusercontent.com/226356/65706525-e3c2b900-e047-11e9-8165-ac9c609f6d8b.png">

**Comment by jaketrent** [comment]
Triage: talking with GP team, this will live in the GP code (not DS).
