### ISSUE TITLE
button: icon not changing color on hover

### ISSUE THREAD

**Issue by dborodyansky** [pluralsight/design-system#67]
![image](https://user-images.githubusercontent.com/3674406/29326085-11088e4e-819f-11e7-8c6b-1b2cc4d1038a.png)

**Comment by jaketrent** [comment]
dashboard.icon.svg and play.icon.svg have a problem: https://pluralsight.slack.com/files/dmitry-borodyansky/F6ZDFQ8QN/play.icon.svg
