### ISSUE TITLE
Correct placeholder text color in dropdown

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#673]
In the dropdown component, the placeholder text should have less contrast than a selected value.

In the dark theme, the placeholder text color is correct, but when a value is selected, the selected value text color is the same as the placeholder.

In the light theme, the placeholder text color is the same dark color as the selected text value.

**Comment by jaketrent** [comment]
Dark theme: make selected text darker
Light theme: make the placeholder text lighter

**Comment by sweeting** [comment]
Designs for this are in PSDS - Web > Components > Input Fields
