### ISSUE TITLE
Tag: event handles aren't supported

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#680]
from @sbking

> I'm using the <Tag> component as a toggle. When you provide an onClick prop, it gets role="button", but it doesn't get a keydown listener for Enter and Space keys. For now I'm just adding those listeners manually, but I feel like it should probably be handled in the Tag component itself for compliance with ARIA

**Comment by EdwardIrby** [comment]
We will revisit this and consider making a ToggleTag. Manual implementation seems correct at the moment.
