### ISSUE TITLE
Position: `inNode` default props doesn't seem to work as expected

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#691]
we set the `inNode` default props based on checking if we're in the browser but it doesn't seem to be worked. exploration needed

reference thread here -> https://pluralsight.slack.com/archives/C70HPSJPP/p1571933105073800

**Comment by EdwardIrby** [comment]
Can't reproduce will update canUseDOM function to be inline with React, 
https://github.com/facebook/react/pull/14194/files
https://github.com/JedWatson/exenv/pull/11
