### ISSUE TITLE
Relax the max length requirement for actionBar on Note

### ISSUE THREAD

**Issue by sbackus** [pluralsight/design-system#701]
https://github.com/pluralsight/design-system/blob/42a926a113dc471215929b7bb3933c827f86de9d/packages/note/src/react/index.js#L255

We want to be able to sometimes add a 3rd button or add a separator between them. 
Currently we're getting warnings about max length of 2 that we'd like to get rid of.

**Comment by danethurber** [comment]
<img width="475" alt="Screen Shot 2019-11-01 at 3 35 59 PM" src="https://user-images.githubusercontent.com/226356/68142320-7b8bb080-feec-11e9-84b7-25187cea2c9b.png">

**Comment by danethurber** [comment]
triage: should this work more like a bonus bar and allow anything?

**Comment by jaketrent** [comment]
Triage: Brian is going to look at current usages in content tools via Tony to see how people want to use it and what we can agree to be consistent on.  This is in pursuit of making a decision: deprecate Note and try something else OR v2 of Note.

**Comment by jaketrent** [comment]
Triage: Brian has completed his audit of teams' usages.  Still trying to figure out how we will proceed (either deprecate Note and try something else OR v2 of Note.).

**Comment by jaketrent** [comment]
Triage: remove action limit.  Nothing else.  Still dragons in the deprecation story.
