### ISSUE TITLE
Multiple Packages: Incorrect Peer Dependencies

### ISSUE THREAD

**Issue by aj-foster** [pluralsight/design-system#707]
## Bug

It appears that the peer dependencies for several packages which were recently updated might have incorrect versions. I'm not familiar enough with the recent changes to know for sure, however.

### Expected behavior

No warnings while installing the packages.

### Actual behavior

Here's a sampling from our application (which would only cover a small subset of the available packages):

```
npm WARN @pluralsight/ps-design-system-button@15.0.0 requires a peer of @pluralsight/ps-design-system-theme@^3.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @pluralsight/ps-design-system-form@4.0.0 requires a peer of @pluralsight/ps-design-system-theme@^3.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @pluralsight/ps-design-system-halo@6.0.0 requires a peer of @pluralsight/ps-design-system-theme@^3.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @pluralsight/ps-design-system-text@14.0.0 requires a peer of @pluralsight/ps-design-system-theme@^3.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @pluralsight/ps-design-system-textarea@4.0.0 requires a peer of @pluralsight/ps-design-system-theme@^3.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @pluralsight/ps-design-system-textinput@5.0.0 requires a peer of @pluralsight/ps-design-system-theme@^3.0.2 but none is installed. You must install peer dependencies yourself.
```

This might be an example of an offending line: [TextArea package.json](https://github.com/pluralsight/design-system/blob/6fccdfc/packages/textarea/package.json#L32). I believe it should allow for version `4.0.0` of the theme package.

### Related packages

- button@15.0.0
- form@4.0.0
- halo@6.0.0
- text@14.0.0
- textarea@4.0.0
- textinput@5.0.0
- Possibly others we aren't using.

### Environment

- OS - MacOS 10.14
- Node.js 10.12.0, npm 6.9.0

**Comment by jaketrent** [comment]
@EdwardIrby Will you comment on the resolution, please?  (eg, how you did/not repro, relevant communication about the fix, and what can be expected now)
