### ISSUE TITLE
Multiple Packages: No longer need `/react` on Import?

### ISSUE THREAD

**Issue by aj-foster** [pluralsight/design-system#708]
## Bug / Question

This is likely related to changes published yesterday. Our current solution is to remove `/react` from our imports, but it's worth confirming that's what you intend.

### Expected behavior

The documentation recommends the following way to import various packages:

```javascript
import {
  PageHeadingLayout,
  AsideLayout,
  EqualColumnLayout
} from '@pluralsight/ps-design-system-layout/react'
```

### Actual behavior

In practice, we receive the following error (using create-react-app):

```
Failed to compile.

./node_modules/@pluralsight/ps-design-system-layout/react.js
Cannot find module: './dist/react'. Make sure this package is installed.

You can install this package by running: npm install ./dist/react.
```

### Related packages

- layout@5.0.0
- Others, and possibly all packages

### Environment

- OS - MacOS 10.14
- Node.js 10.12.0, npm 6.9.0

**Comment by EdwardIrby** [comment]
@aj-foster looks like a few of cjs paths didn't get updated. Thanks for finding that. Removing *react* is intended for if you want to take advantage of treeshaking on your webpack/parcel/rollup bundles.
