### ISSUE TITLE
Row/Card: truncate metadata lines instead of each item in the line

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#709]
Currently we truncate each item in the metadata lines in rows and cards. Instead we should truncate the entire line and the truncation should happen based on the container rather than a max width of the line.

In some cases, author names (especially when there are multiple) can be quite long. I suppose people might still want to truncate those, but not sure if that should be done as part of the component or not.

![Card   Row Metadata Truncation](https://user-images.githubusercontent.com/48542/68964281-31c98280-0796-11ea-8e36-b4a18c1bf32a.png)

**Comment by jaketrent** [comment]
Triage:  Truncate single line; Card still handles separators

**Comment by EdwardIrby** [comment]
After talking with @sweeting, we decided dev can truncate the author names for example if they need to.

**Comment by EdwardIrby** [comment]
After further discussion we are closing for now and will revisit. Tooltips are not a viable solution for mobile usage. Need to encourage users to choose what they should emphasize rather than placing everything in metadata rows.
