### ISSUE TITLE
dialog: Inner dimensions too large when using a Dropdown

### ISSUE THREAD

**Issue by MCluck90** [pluralsight/design-system#779]
### Expected behavior

See a `Dropdown` inside of the `Dialog` without resizing the `Dialog`

### Actual behavior

Scrollbars appear on the `Dialog`. When opening the `Dropdown`, the internal dimensions of the `Dialog` become as large as the viewport.

Before opening the `Dropdown`:

![Before opening the dropdown](https://raw.githubusercontent.com/MCluck90/dropdown-in-dialog-ps-design-system/master/screenshots/initial.png)

After opening the `Dropdown`:

![After opening the dropdown](https://raw.githubusercontent.com/MCluck90/dropdown-in-dialog-ps-design-system/master/screenshots/open.png)

[Repository which reproduces the problem](https://github.com/MCluck90/dropdown-in-dialog-ps-design-system)

### Steps to repro

1. Create a basic `Dialog` (ex. `<Dialog aria-label="Dialog"> ... </Dialog>`)
2. [Copy the example code for a `Dropdown`](https://design-system.pluralsight.com/components/dropdown)
3. Paste the code in to the `Dialog`

### Related packages

- actionmenu@^9.0.9
- core@^5.1.0
- dialog@^7.0.13
- dropdown@^5.0.11

### Environment

- OS - Windows 10
- Browser version - Chrome v79

**Comment by jaketrent** [comment]
Triage: scroll dimensions possibly from the dropdown overlay.  Overlay's gone now. Maybe not still a problem.  If is, potentially bug.  We'll check it out.
