### ISSUE TITLE
dropdown: selection persists when value changes

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#876]
initial thread here => https://pluralsight.slack.com/archives/C70HPSJPP/p1580926951114300

i paired with the hawkeye team and validated the issue. unsure of the cause

example code with bug is here -> https://github.com/ps-dev/search/blob/wip-dropdown-attempt1/ui/src/frontend/App/components/Home/components/TabsBar/components/Filters/components/LevelFilter/LevelFilter.tsx

**Comment by danethurber** [comment]
was able to reproduce the bug here => https://codesandbox.io/s/morning-snowflake-p0jcb

providing a new value does not change the selected item

**Comment by jaketrent** [comment]
Modified your example to get it to work:
https://codesandbox.io/s/blissful-bush-0p106

I'm modifying the in-app example in the docs to have the "set with button" scenario too.

In this case, that wasn't the problem though.  It was just that there were value attributes on the items for the dropdown, so dropdown didn't know which to select when asked.

**Comment by danethurber** [comment]
wasn't actually a bug. a value on the Menu.Item was needed to marry the group value with item value. I worked with the team and adding the value worked
