### ISSUE TITLE
tab: does not honor psds2020Colors flag

### ISSUE THREAD

**Issue by MCluck90** [pluralsight/design-system#891]
### Expected behavior

The active tab remains orange while the psds2020Colors feature flag is not enabled.

### Actual behavior

![psds2020Colors-tab](https://user-images.githubusercontent.com/1753801/74195131-d7668380-4c17-11ea-8c19-a1c4c4d50b0b.png)

### Steps to repro

1. Create an app without the `FeatureFlags` component
2. Create a set of tabs
3. The active tab will appear blue instead of the original orange

### Related packages

- tab@14.0.24

### Environment

- OS - Windows 10
- Browser version - Chrome v79

**Comment by jaketrent** [comment]
Hey Mike, This is as designed.  Tab and all other DS components have been updated to the new 2020 colors.  But there are only 3 in the "First Wave" that are using the flag: Button, Link, and Text.  In 2 days, the flag is on by default and will be gone for them as well.

Please feel free to use Tab as it is.

Closing as a non-issue.  Please reopen or chat with questions.

**Comment by jaketrent** [comment]
For reference, 2020 color faq https://docs.google.com/document/d/1vVA0mXFcLXMXIxKmSQIawYqnDT-2y4uqElUI4S-0hd0/edit#
