### ISSUE TITLE
site: colors js example

### ISSUE THREAD

**Issue by EdwardIrby** [pluralsight/design-system#897]
Our docs are missing an example of how to import the colors from core as js

**Comment by jaketrent** [comment]
Color usage by js is already present.  

https://design-system.pluralsight.com/core/color#usage

Per variable is not present:

import { 
  colorsBlue, 
} from "@pluralsight/ps-design-system-core";

style={{ color: colorsBlue.base }}

Perhaps on the docs swatches:

JS: colorsBlue.base
CSS: psColorsBlueBase

Triage: Assigning Brian to work on docs design.

**Comment by sweeting** [comment]
Add a line for JS variable name and use "JS:" and "CSS:" prefixes.
![image](https://user-images.githubusercontent.com/48542/74880962-a1b54f00-5329-11ea-93c4-7448a2c2a1ad.png)
