### ISSUE TITLE
button: ref isn't passed onto base button element

### ISSUE THREAD

**Issue by bressain** [pluralsight/design-system#91]
### Expected behavior

Probably a borderline "bug". For situations where you need a ref to the base component element, I would expect that setting the `ref` prop would give back an element.

**Workaround:** Using `innerRef` appears to work

### Actual behavior

When setting the `ref` prop to a function, the resulting element returned is null.

```jsx
setElement = el => {
  // el comes back as null :-(
  this.buttonElement = el
}
...
<Button ref={this.setElement}>Ohai!</Button>
```

### Steps to repro

1. Set `ref` on the `Button` component with a callback.
2. Run the app and see that the callback is given null.

### Related packages

- button@8.0.1

### Environment

- OS - MacOS 10.12
- Browser version - Chrome v60

**Comment by jaketrent** [comment]
I’d use innerRef for now to go forward, but what I’d like to do is use `ref` on the design system and let the button do the `ref`->`innerRef` translation internally.

When I do/break that, I’ll give you a new major version

**Comment by jaketrent** [comment]
This applies to probably most components.

**Comment by bressain** [comment]
@jaketrent looks like the latest version of the button (8.1.1) broke the ability to use `innerRef`. Getting a warning from React as well:
```
Warning: Unknown prop `innerRef` on <button> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

**Comment by jaketrent** [comment]
@bressain Sorry, I think I may have created a breaking change without indicating such in the version.  Have you tried plain `ref`?  Does it work now?

**Comment by bressain** [comment]
@jaketrent `ref` does not work (sends null to my ref function).

**Comment by jaketrent** [comment]
:( k, i'll check it out

**Comment by jaketrent** [comment]
@bressain `innerRef` should work as before now in button@9.0.3  .  Please give it a try and let me know.

**Comment by bressain** [comment]
Looks like it's working again, thanks!
