### ISSUE TITLE
Icons: Add Labs icon

### ISSUE THREAD

**Issue by bleakley-ps** [pluralsight/design-system#916]
###  Enhancement Request

We would like this Labs icon to be added.

### Desired behavior

We would like this icon to be available.

[labs-icon.svg.zip](https://github.com/pluralsight/design-system/files/4257317/labs-icon.svg.zip)

### Today's behavior

We have to use our own svg

### The Value Add

If the icon is not in the design system, another BC might use a different icon for labs elsewhere, and that would create an inconsistent experience.

### The Tradeoffs

Nothing!

**Comment by jaketrent** [comment]
@sweeting Does this feel like an icon others would like to use as well?

**Comment by sweeting** [comment]
I think it's appropriate to add.

@bleakley-ps The icon svg you attached is 16x16. The other icons in our set are 24x24. Can you point me to the designer who provided you with the icon so I can work with them to make sure it matches the rest of our set?

**Comment by bleakley-ps** [comment]
Thanks! It was made by Bryan Bishop.

**Comment by sweeting** [comment]
The labs icon has been added to the PSDS - Icons figma file.
