### ISSUE TITLE
position: Position/Tooltip miscalculation

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#932]
> I think there's some kind of bug in the [Position|Tooltip] element (not sure which, but thinking Position). If you got to https://app-stage.pluralsight.com/plan-analytics/1800contacts/skills the info icon as shown below should show a tooltip. It works when the browser window has plenty of space to the right. When the browser window width shrinks, it takes a few mouse overs for the position to get calculated correctly. If you start out with a smaller browser width, the tip does not even show at all until you've moused in and out a lot while something is calibrating position and size and eventually the tip starts to show up, narrowing in on the correct position. (edited) 

cc https://pluralsight.slack.com/archives/C70HPSJPP/p1584550569101100

**Comment by jaketrent** [comment]
Triage: haven't looked at closely enough to repro yet.  Pick it up and figure out if it's an issue with the component.

**Comment by EdwardIrby** [comment]
Can't reproduce this. I need to see the code used to implement tooltip in staging.

**Comment by jaketrent** [comment]
This has come back up on another page.  Seems like a reproducible problem, somehow.

**Comment by nfpiche** [comment]
Here's a repro on codesandbox, interestingly enough it only happens on the right side of the screen.
https://codesandbox.io/s/festive-noyce-38298
