### ISSUE TITLE
ps-design-system-table: Better sorting handling

### ISSUE THREAD

**Issue by matthewma7** [pluralsight/design-system#934]
## Enhancement Request

Note: Here are two separate but related feature requests denoted by number 1 and 2

### Desired behavior

1. Pass original event to onClick handler for `<Table.ColumnHeader />`
2. Add un sort prop option

### Today's behavior

1. onClick event only pass sortDir, one argument
2. It can only sort between `asc` and `desc`, can't unsort

### The Value Add

1. This helps detect if a modifier key is pressed to handle sorting by multiple columns
2. Make it possible to unsort a column

### The Tradeoffs

No obvious tradeoffs

**Comment by EdwardIrby** [comment]
- Break change pass event as the first param and sort direction as the second parameter. 
- Will revisit on the un sort.
@matthewma7 please contact @sweeting to provide further information about un sort use case.

**Comment by jaketrent** [comment]
Idea: Just pass original event as 2nd param, don't need to make breaking change.  We have event passed last on lots of other components, nbd.

**Comment by matthewma7** [comment]
I think what @jaketrent describes would work for my use case.

**Comment by jaketrent** [comment]
Matthew, we think this is done.  We did the event add to the column sort handler.  We are still unsure about what unsort could/should do.  We'll close this for now.  If you still need support, please contact us with more unsort details directly.
