### ISSUE TITLE
action menu: onClose prop overlay blocks the menu itself

### ISSUE THREAD

**Issue by matthewma7** [pluralsight/design-system#939]
### Expected behavior
Can interact with menu items

### Actual behavior
Can not interact with menu items
BTW: It seems [there is a prop](https://github.com/pluralsight/design-system/blob/494d6ccd7dac258c7420ab4d501c9a121ff1c3c6/packages/carousel/src/react/__stories__/index.story.js#L240) added by accident

### Steps to repro

1. Create an ActionMenu instance with onClose prop
2. Try to interact with ActionMenu.Items

### Related packages

- actionmenu@11.0.3

### Environment

- OS - MacOS 10.15
- Browser version - Chrome v80

**Comment by EdwardIrby** [comment]
Should of been resolved by #975
