### ISSUE TITLE
ps-design-system-textinput: className class is applied to label and input elements

### ISSUE THREAD

**Issue by BenGu3** [pluralsight/design-system#940]
### Expected behavior

When `<TextInput>` is given a `className`, it applies that class to **only** the `<label>`, not the `<input>`.

### Actual behavior

The class is applied to both the `<label>` and the `<input>`.

### Steps to repro

https://codesandbox.io/s/nervous-thunder-ormdu

1. Add a className to a `<TextInput>`.

### Environment

- OS - MacOS 10.15.4
- Browser version - Chrome v80

**Comment by EdwardIrby** [comment]
Make breaking change move className only to label.
