### ISSUE TITLE
Typeahead: getSuggestionLabel function should default to sug.props.label

### ISSUE THREAD

**Issue by finetimi** [pluralsight/design-system#945]
## Bug

Typeahead `getSuggestionLabel` function currently returns `sug.props.children`.
https://github.com/pluralsight/design-system/blob/f961b0c3314e78284cbdebbacaa62cbca5861f66/packages/typeahead/src/react/index.js#L181

Screenshots/casts are helpful
Link to your source code in your application repo

### Steps to repro

1. https://github.com/pluralsight/design-system/blob/f961b0c3314e78284cbdebbacaa62cbca5861f66/packages/typeahead/src/react/index.js#L181

### Related packages
- typeahead@3.310

## Enhancement Request
Function should be
```javascript
function getSuggestionLabel(sug) {
  return sug.props.label || sug.props.children
}
```
### Desired behavior
```javascript
function getSuggestionLabel(sug) {
  return sug.props.label || sug.props.children
}
```
Support you wish you had.

### Today's behavior
```javascript
function getSuggestionLabel(sug) {
  return  sug.props.children
}
```

**Comment by EdwardIrby** [comment]
Recommend documenting value prop which should accomplish goal.
