### ISSUE TITLE
Dropdown: unable to use mouse to select dropdown options when it's inside a form.

### ISSUE THREAD

**Issue by sweeting** [pluralsight/design-system#958]
### Bug
Unable to select items in dropdown with the mouse when it's inside a form.

![Kapture 2020-04-03 at 16 15 06](https://user-images.githubusercontent.com/48542/78409278-754a4f00-75c6-11ea-8f75-3ce7af1d90e0.gif)

### Expected behavior
I could select an item in the dropdown/action menu by clicking the option with the mouse.

### Actual behavior
I can only select options in the dropdown using the arrow keys.

### Steps to repro
Try to select an option in the dropdown in an in-app example by clicking with your mouse. 

- [Dropdown docs](https://design-system.pluralsight.com/components/dropdown#in-app-example)
- [Form docs](https://design-system.pluralsight.com/components/form#in-app-example)

### Related packages
- dropdown@6.0.6

### Environment

- OS - MacOS 10.14
- Browser version - Safari/Chrome (latest)

**Comment by madams1** [comment]
I think this is an issue with ActionMenu... was able to select from the dropdown (with mouse and keyboard) by reverting to ActionMenu v9.1.8
